#!/usr/bin/env python3
"""Figures for the gpl runtime study, drawn from perf_summary.py JSONs.

Same conventions as test/pre_route_pessimism/plots.py: Agg backend, PNGs
regenerated by a run rather than edited, fixed categorical slots, one axis
per panel, recessive grid.

  plots.py timeline  run.json -o busy.png     busy threads over the run
  plots.py symbols   run.json -o syms.png     self-time share per function
  plots.py sweep     a.json b.json ... -o sweep.png   wall vs threads
  plots.py phases    a.json b.json ... -o phases.png  wall per phase, per run
  plots.py categories run.json -o cat.png            CPU samples by code category
  plots.py walltargets callgraph.json -o wall.png    main-thread wall by target,
                                                     split serial / parallel / waiting
"""

import argparse
import json
import re

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

SERIES = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300"]
SURFACE = "#fcfcfb"
INK = "#0b0b0b"
INK_2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
AXIS = "#c3c2b7"
BAND = "#cde2fb"

PHASE_LABEL = {
    "load": "load_design",
    "gpl_setup": "gpl setup",
    "initial_place": "initial place",
    "nesterov": "Nesterov",
    "place_pins": "place_pins",
    "write_db": "write_db",
}
PHASE_ORDER = [
    "load",
    "gpl_setup",
    "initial_place",
    "nesterov",
    "place_pins",
    "write_db",
]


def style(ax):
    ax.set_facecolor(SURFACE)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS)
    ax.tick_params(colors=INK_2, labelsize=9)
    ax.grid(True, color=GRID, linewidth=0.6)
    ax.set_axisbelow(True)


def shorten(sym, width=58):
    sym = re.sub(r"\(.*\)$", "()", sym)
    sym = sym.replace("std::__1::", "std::")
    return sym if len(sym) <= width else sym[: width - 1] + "…"


def timeline(runs, out, title):
    fig, ax = plt.subplots(figsize=(9, 3.6), dpi=160)
    fig.patch.set_facecolor(SURFACE)
    style(ax)
    for i, run in enumerate(runs):
        eff = run["effective_threads"]
        label = run.get("label", f'{run["run"].get("threads", "")} threads')
        ax.plot(
            range(len(eff)), eff, color=SERIES[i % 6], linewidth=1.0, label=str(label)
        )
        busy = run["busy_threads"]
        if i == 0:
            ax.plot(
                range(len(busy)),
                busy,
                color=SERIES[i % 6],
                linewidth=0.7,
                linestyle=":",
                label="threads alive (incl. spinning)",
            )
    run = runs[0]
    phases = sorted(run.get("phases", {}).items(), key=lambda kv: kv[1])
    top = max((max(r["busy_threads"]) for r in runs), default=1)
    for (name, t0), nxt in zip(phases, phases[1:] + [(None, len(run["busy_threads"]))]):
        if nxt[1] - t0 < 0.02 * len(run["busy_threads"]):
            continue
        ax.axvline(t0, color=AXIS, linewidth=0.7, linestyle=":")
        ax.text(
            (t0 + nxt[1]) / 2,
            top * 1.04,
            PHASE_LABEL.get(name, name),
            ha="center",
            va="bottom",
            fontsize=8,
            color=INK_2,
        )
    threads = int(run["run"].get("threads", 0) or 0)
    if threads:
        ax.axhline(threads, color=MUTED, linewidth=0.7, linestyle="--")
    ax.set_xlabel("elapsed s", color=INK_2)
    ax.set_ylabel("thread-equivalents doing work", color=INK_2)
    ax.set_ylim(0, max(top, threads) * 1.18)
    ax.set_title(title, color=INK, fontsize=11, loc="left")
    ax.legend(frameon=False, fontsize=8, loc="upper right")
    fig.tight_layout()
    fig.savefig(out, facecolor=SURFACE)


def phases(runs, out, title):
    runs = sorted(runs, key=lambda r: int(r["run"]["threads"]))
    labels = [r.get("label", f'{r["run"]["threads"]}') for r in runs]
    fig, ax = plt.subplots(figsize=(9, 3.6), dpi=160)
    fig.patch.set_facecolor(SURFACE)
    style(ax)
    bottom = [0.0] * len(runs)
    for i, ph in enumerate(PHASE_ORDER):
        vals = [r["phase_seconds"].get(ph, 0.0) for r in runs]
        if not any(vals):
            continue
        ax.bar(
            labels,
            vals,
            bottom=bottom,
            color=SERIES[i % 6],
            width=0.6,
            label=PHASE_LABEL.get(ph, ph),
        )
        bottom = [b + v for b, v in zip(bottom, vals)]
    for x, total in zip(labels, bottom):
        ax.text(
            x,
            total,
            f"{total:.0f} s",
            ha="center",
            va="bottom",
            fontsize=8,
            color=INK_2,
        )
    ax.set_xlabel("threads", color=INK_2)
    ax.set_ylabel("wall s", color=INK_2)
    ax.set_title(title, color=INK, fontsize=11, loc="left")
    ax.set_ylim(0, max(bottom) * 1.25)
    ax.legend(frameon=False, fontsize=8, ncol=3, loc="upper left")
    fig.tight_layout()
    fig.savefig(out, facecolor=SURFACE)


def categories(run, out, title):
    cats = run["categories"][::-1]
    fig, ax = plt.subplots(figsize=(9, 0.32 * len(cats) + 1.2), dpi=160)
    fig.patch.set_facecolor(SURFACE)
    style(ax)
    colors = [SERIES[1] if c["category"] == "OpenMP wait" else SERIES[0] for c in cats]
    ax.barh(
        [c["category"] for c in cats],
        [100 * c["share"] for c in cats],
        color=colors,
        height=0.7,
    )
    ax.set_xlabel("% of openroad CPU samples", color=INK_2)
    ax.set_title(title, color=INK, fontsize=11, loc="left")
    fig.tight_layout()
    fig.savefig(out, facecolor=SURFACE)


def walltargets(cg, out, title, top=14, wall_s=None):
    rows = cg["main_targets"][:top][::-1]
    scale = 100.0 if wall_s is None else wall_s
    unit = "% of wall" if wall_s is None else "wall s"
    labels = [
        f'{r["phase"]}: {shorten(r["target"].replace("  [self]", ""), 46)}'
        for r in rows
    ]
    fig, ax = plt.subplots(figsize=(9.5, 0.34 * len(rows) + 1.4), dpi=160)
    fig.patch.set_facecolor(SURFACE)
    style(ax)
    left = [0.0] * len(rows)
    for key, color, name in (
        ("serial", SERIES[1], "serial: one thread working"),
        ("parallel", SERIES[0], "inside a parallel region"),
        ("waiting", MUTED, "master waiting at barrier"),
    ):
        vals = [scale * r[key] for r in rows]
        ax.barh(labels, vals, left=left, color=color, height=0.7, label=name)
        left = [a + b for a, b in zip(left, vals)]
    ax.set_xlabel(unit, color=INK_2)
    ax.tick_params(axis="y", labelsize=7.5)
    ax.set_title(title, color=INK, fontsize=11, loc="left")
    ax.legend(frameon=False, fontsize=8, loc="lower right")
    fig.tight_layout()
    fig.savefig(out, facecolor=SURFACE)


def symbols(run, out, title, top=25):
    syms = run["symbols"][:top][::-1]
    fig, ax = plt.subplots(figsize=(9, 0.28 * len(syms) + 1.2), dpi=160)
    fig.patch.set_facecolor(SURFACE)
    style(ax)
    ax.barh(
        [shorten(s["symbol"]) for s in syms],
        [100 * s["share"] for s in syms],
        color=SERIES[0],
        height=0.7,
    )
    ax.set_xlabel("% of openroad CPU samples (self time)", color=INK_2)
    ax.set_title(title, color=INK, fontsize=11, loc="left")
    ax.tick_params(axis="y", labelsize=7.5)
    fig.tight_layout()
    fig.savefig(out, facecolor=SURFACE)


def sweep(runs, out, title):
    runs = sorted(runs, key=lambda r: int(r["run"]["threads"]))
    n = [int(r["run"]["threads"]) for r in runs]
    wall = [r["wall_s"] for r in runs]
    fig, axes = plt.subplots(1, 2, figsize=(9, 3.4), dpi=160)
    fig.patch.set_facecolor(SURFACE)
    for ax in axes:
        style(ax)
    axes[0].plot(
        n, wall, "o-", color=SERIES[0], linewidth=1.0, markersize=4, label="measured"
    )
    t1 = wall[0]
    # Amdahl fit through the 1-thread and max-thread points.
    if len(n) > 1 and n[0] == 1:
        nmax, tmax = n[-1], wall[-1]
        serial = (tmax / t1 - 1 / nmax) / (1 - 1 / nmax)
        fit = [t1 * (serial + (1 - serial) / k) for k in n]
        axes[0].plot(
            n,
            fit,
            "--",
            color=SERIES[1],
            linewidth=0.9,
            label=f"Amdahl, serial fraction {serial:.0%}",
        )
        axes[0].legend(frameon=False, fontsize=8)
    axes[0].set_xscale("log", base=2)
    axes[0].set_xticks(n)
    axes[0].set_xticklabels([str(k) for k in n])
    axes[0].set_xlabel("threads", color=INK_2)
    axes[0].set_ylabel("wall s", color=INK_2)
    axes[1].plot(
        n, [t1 / w for w in wall], "o-", color=SERIES[0], linewidth=1.0, markersize=4
    )
    axes[1].plot(n, n, ":", color=MUTED, linewidth=0.8)
    axes[1].set_xscale("log", base=2)
    axes[1].set_xticks(n)
    axes[1].set_xticklabels([str(k) for k in n])
    axes[1].set_xlabel("threads", color=INK_2)
    axes[1].set_ylabel("speedup over 1 thread", color=INK_2)
    fig.suptitle(title, color=INK, fontsize=11, x=0.01, ha="left")
    fig.tight_layout()
    fig.savefig(out, facecolor=SURFACE)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "kind",
        choices=["timeline", "symbols", "sweep", "phases", "categories", "walltargets"],
    )
    ap.add_argument(
        "--wall", type=float, help="walltargets: scale shares to this many seconds"
    )
    ap.add_argument("runs", nargs="+")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--title", default="")
    ap.add_argument("--labels", help="comma-separated series labels")
    args = ap.parse_args()
    runs = [json.load(open(p)) for p in args.runs]
    if args.labels:
        for run, label in zip(runs, args.labels.split(",")):
            run["label"] = label
    if args.kind == "timeline":
        timeline(runs, args.output, args.title)
    elif args.kind == "symbols":
        symbols(runs[0], args.output, args.title)
    elif args.kind == "phases":
        phases(runs, args.output, args.title)
    elif args.kind == "categories":
        categories(runs[0], args.output, args.title)
    elif args.kind == "walltargets":
        walltargets(runs[0], args.output, args.title, wall_s=args.wall)
    else:
        sweep(runs, args.output, args.title)


if __name__ == "__main__":
    main()
