"""analysistest: AUTO_MEMORIES declares its generated views as outputs.

ORFS's AUTO_MEMORIES writes results/memories.json and a
results/memories/ directory of generated .lib/.lef views during
canonicalization, and every later stage reads them back by globbing the
results dir (load.tcl, read_liberty.tcl). In a sandbox only declared
outputs survive, so if the synth rule does not declare them the views
are discarded the moment canonicalization ends and floorplan fails to
link the blackboxed memory modules.

The negative half matters as much as the positive one: a design without
AUTO_MEMORIES must declare neither, or every design in the world pays
for a directory artifact and a JSON it never produces -- and the action
would fail for not creating them.

Declaring them is necessary and not sufficient, which is the other half
of this file. The views have to reach the action that reads them back,
and for a long time they did not: the serial synthesis path carried
them into the ODB action and the parallel path did not, so every design
with SYNTH_NUM_PARTITIONS set -- the default -- generated correct macro
views, discarded them at the sandbox boundary, and failed with

    [ERROR ORD-2013] instance u_dmem LEF master cmj_dmem not found

`consumed` asserts the other end of that, so a path that declares the
views but does not feed them fails here instead of in OpenROAD.

Its coverage is honest but partial, and the gap is worth naming: the
only design in reach with AUTO_MEMORIES=1 is asap7/tinyRocket, which
does not set SYNTH_HIERARCHICAL and therefore takes the serial path --
the one that was always correct. Catching the parallel-path regression
in this file needs a design that sets both, and there is none. Until
there is, the parallel path is covered only end to end, by the designs
in //test/coremark_joule that harden a program memory.
"""

load("@bazel_skylib//lib:unittest.bzl", "analysistest", "asserts")

def _output_basenames(env):
    names = {}
    for action in analysistest.target_actions(env):
        for f in action.outputs.to_list():
            names[f.basename] = action.mnemonic
    return names

def _consumed_basenames(env, produced):
    """Basenames of `produced` that some action also takes as an input.

    An artifact that is declared but consumed by nothing is discarded at
    the sandbox boundary, which is indistinguishable from never having
    been generated by the time OpenROAD looks for it.
    """
    consumed = {}
    for action in analysistest.target_actions(env):
        for f in action.inputs.to_list():
            if f.basename in produced:
                consumed[f.basename] = True
    return consumed

def _auto_memories_outputs_test_impl(ctx):
    env = analysistest.begin(ctx)
    declared = _output_basenames(env)
    label = analysistest.target_under_test(env).label

    for name in ctx.attr.expected:
        asserts.true(
            env,
            name in declared,
            ("Expected %s among the declared outputs of %s, but it is " +
             "absent. Declared: %s") % (name, label, sorted(declared)),
        )

    if ctx.attr.consumed:
        consumed = _consumed_basenames(env, {n: True for n in ctx.attr.consumed})
        for name in ctx.attr.consumed:
            asserts.true(
                env,
                name in consumed,
                ("%s is declared by %s but no action consumes it, so it " +
                 "is discarded at the sandbox boundary and the stage " +
                 "that globs it out of the results dir finds nothing.") %
                (name, label),
            )

    for name in ctx.attr.forbidden:
        asserts.true(
            env,
            name not in declared,
            ("%s is declared as an output of %s, which does not set " +
             "AUTO_MEMORIES=1. Nothing produces it, so the action would " +
             "fail for not creating it.") % (name, label),
        )

    return analysistest.end(env)

auto_memories_outputs_test = analysistest.make(
    _auto_memories_outputs_test_impl,
    attrs = {
        "expected": attr.string_list(
            doc = "Output basenames that must be declared.",
        ),
        "consumed": attr.string_list(
            doc = "Declared output basenames that some action must also " +
                  "take as an input.",
        ),
        "forbidden": attr.string_list(
            doc = "Output basenames that must NOT be declared.",
        ),
    },
)
