#!/usr/bin/env python3
"""Emit a Verilog design whose only purpose is to have many registers.

The asap7 platform constraints say `-from [all_inputs] -to [all_registers]`
(three set_max_delay, four group_path).  write_sdc has no way to say
"all registers", so every one of those lines is expanded into an explicit
list of every register clock pin in the design.  The size of the generated
.sdc, and the time read_sdc spends resolving it, therefore scale with the
register count -- not with the port count.  This generator makes that
register count a parameter so the cost can be measured as a curve.

    gen_sdc_scale.py <flops> <bus width> <out.v>

The design is a W-bit input bus, a chain of N/W W-bit pipeline stages and a
W-bit output bus: N flops that no optimizer can remove, three-plus-2W ports.
"""
import sys


def main() -> None:
    flops, width, out = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
    stages = max(1, flops // width)
    with open(out, "w") as f:
        f.write(
            "// Generated by gen_sdc_scale.py: %d flops as %d stages of %d bits.\n"
            % (stages * width, stages, width)
        )
        f.write("module sdc_scale (\n")
        f.write("  input  wire             clock,\n")
        f.write("  input  wire             reset,\n")
        f.write("  input  wire [%d:0] din,\n" % (width - 1))
        f.write("  output wire [%d:0] dout\n" % (width - 1))
        f.write(");\n")
        f.write("  reg [%d:0] stage [0:%d];\n" % (width - 1, stages - 1))
        f.write("  integer i;\n")
        f.write("  always @(posedge clock) begin\n")
        f.write("    if (reset) begin\n")
        f.write("      for (i = 0; i < %d; i = i + 1) stage[i] <= %d'd0;\n" % (stages, width))
        f.write("    end else begin\n")
        f.write("      stage[0] <= din;\n")
        f.write("      for (i = 1; i < %d; i = i + 1) stage[i] <= stage[i-1];\n" % stages)
        f.write("    end\n")
        f.write("  end\n")
        f.write("  assign dout = stage[%d];\n" % (stages - 1))
        f.write("endmodule\n")


if __name__ == "__main__":
    main()
