#! /bin/sh
set -e

if [ -z "$FLOW_HOME" ]; then
  export MAKE_PATH="${MAKE_PATH}"
  # Yosys-stage runners pass yosys_substitutions(ctx) and get a concrete
  # ${YOSYS_PATH} substituted in. Openroad-stage runners (orfs_final etc.)
  # use only flow_substitutions(ctx) and leave ${YOSYS_PATH} as a literal,
  # which the shell then expands to empty. Only export YOSYS_EXE when
  # we actually got a path; otherwise fall back to the caller's env so
  # `bazel run :_final -- SYNTH_NETLIST_FILES=...` (used by
  # //:make-yosys-netlist for re-synth) can supply yosys via YOSYS_EXE
  # from the user shell.
  if [ -n "${YOSYS_PATH}" ]; then
    export YOSYS_EXE="${YOSYS_PATH}"
  fi
  # A caller-supplied OPENROAD_EXE wins. Pointing a deployed reproducer at
  # a locally built openroad is what the _deps tarball is for, and the
  # deployed tree is the one place the binary is not a bazel label.
  if [ -n "${OPENROAD_EXE:-}" ]; then
    _openroad_exe="$OPENROAD_EXE"
  else
    # Select the Qt-linked openroad only when the caller asked for a
    # gui_* make target. Build-time stages and the portable tarball
    # invoke CLI make targets and therefore keep ${OPENROAD_PATH}.
    _openroad_exe="${OPENROAD_PATH}"
    for _arg in "$@"; do
      case "$_arg" in
        gui_*|gui-*) _openroad_exe="${OPENROAD_QT_PATH}"; break ;;
      esac
    done
  fi
  export OPENROAD_EXE="$_openroad_exe"
  export OPENSTA_EXE="${OPENSTA_PATH}"
  export KLAYOUT_CMD="${KLAYOUT_PATH}"
  export STDBUF_CMD="${STDBUF_PATH}"
  export FLOW_HOME="${FLOW_HOME}"
else
  # if make is not in the path, error out, otherwise set MAKE_PATH
  if ! command -v make >/dev/null; then
    echo "Error: make is not in the PATH"
    exit 1
  fi
  export MAKE_PATH="$(command -v make)"
fi

# https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/3907
export LEC_CHECK=0

# Default to offscreen Qt platform when no display server is available.
if [ -z "${DISPLAY:-}" ] && [ -z "${WAYLAND_DISPLAY:-}" ]; then
  export QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-offscreen}"
fi

# A deployed tree holds one stage's inputs as bazel built them. A bare
# stage target (`floorplan`, `place`, ...) lets ORFS's dependency chain
# decide that upstream results are stale and rebuild them here, from
# inputs bazel never gave the tree, and the tree stops matching the
# build. The honest targets are `do-<stage>`, which run that stage and
# nothing else; `run`, `open_*` and `gui_*` pass. Stop before make does.
for _arg in "$@"; do
  case "$_arg" in
    synth|floorplan|place|cts|grt|route|final|generate_abstract|all|clean_all)
      echo "make: refusing target '$_arg' in a deployed tree: it would rebuild upstream" >&2
      echo "      stages from inputs bazel never gave this tree. Run one stage:" >&2
      echo "      ./make do-$_arg   (do-synth, do-floorplan, do-place, do-cts, do-grt, do-route, do-final)" >&2
      exit 2
      ;;
  esac
done
# A deployed tree is one stage's tree, and it may run that stage only.
#
# The fence, so it is not relitigated: bazel scopes each stage's config.mk
# to the variables of that stage, because config.mk is an input of the
# stage's action and so part of its cache key; a CTS knob must not re-run
# the floorplan. The deployed tree ships that same stage-scoped config, so
# `do-place` in a floorplan tree runs the place stage with ORFS defaults
# for every place variable the design set (ENABLE_DPO, DETAIL_PLACEMENT_ARGS,
# ...), silently, and the output does not match the design. Shipping the
# union of all stages' variables instead is not the fix: a stage's config is
# built from the previous stage's OrfsInfo argument set plus its own
# orfs_arguments, and an orfs_arguments target can be generated by an
# action from an earlier stage's outputs, so a later stage's variables exist
# only after the earlier stages have run in bazel. A union taken at deploy
# time carries the static ones and drops the generated ones without a word.
# It would work for a simple flow and fail in exactly the complicated flows
# where the shortcut is most tempting. Iterate a stage in that stage's own
# `_deps` tree. ORFS_DEPLOY_ANY_STAGE=1 runs the target anyway, for the
# caller who supplies the later stage's variables by hand, and says so.
_deploy_stage="${DEPLOY_STAGE}"
if [ -n "$_deploy_stage" ]; then
  case "$_deploy_stage" in
    synth)     _own="do-synth|do-yosys*|do-1_synth*|do-1_1_*|do-1_2_*" ;;
    floorplan) _own="do-floorplan|do-2_*|do-1_3_floorplan_to_place" ;;
    place)     _own="do-place|do-3_*" ;;
    cts)       _own="do-cts|do-4_*" ;;
    grt)       _own="do-grt|do-5_1_*" ;;
    route)     _own="do-route|do-5_2_*|do-5_3_*" ;;
    final|gds) _own="do-final|do-6_*|do-gds*" ;;
    abstract)  _own="do-generate_abstract|do-7_*" ;;
    *)         _own="" ;;
  esac
  for _arg in "$@"; do
    case "$_arg" in
      do-synth|do-floorplan|do-place|do-cts|do-grt|do-route|do-final|do-generate_abstract|do-yosys*|do-[1-7]_*) ;;
      *) continue ;;
    esac
    _ok=0
    if [ -n "$_own" ]; then
      _saved_ifs="$IFS"; IFS='|'
      for _pat in $_own; do
        IFS="$_saved_ifs"
        case "$_arg" in $_pat) _ok=1 ;; esac
        IFS='|'
      done
      IFS="$_saved_ifs"
    fi
    if [ "$_ok" -eq 0 ]; then
      if [ "${ORFS_DEPLOY_ANY_STAGE:-0}" = "1" ]; then
        echo "make: WARNING: '$_arg' is not a $_deploy_stage target; this tree (${DEPLOY_LABEL}) was deployed for the $_deploy_stage stage" >&2
        echo "      and carries only its variables. ORFS_DEPLOY_ANY_STAGE=1: running it with the later stage's variables you supply." >&2
      else
        echo "make: refusing '$_arg': this tree (${DEPLOY_LABEL}) was deployed for the $_deploy_stage stage and carries" >&2
        echo "      only that stage's variables. A later stage's variables are produced by the stages before it and" >&2
        echo "      exist only in that stage's own deploy tree:" >&2
        echo "        bazelisk run <flow>_<stage>_deps -- --install <dir>    (the _deps target of the stage you want, same flow)" >&2
        echo "      ORFS_DEPLOY_ANY_STAGE=1 runs it here anyway, with the later stage's variables supplied by you." >&2
        exit 2
      fi
    fi
  done
fi
exec $MAKE_PATH --file "$FLOW_HOME/Makefile" "$@"
