--- OpenROAD-flow-scripts/flow/Makefile
+++ OpenROAD-flow-scripts/flow/Makefile
@@ -1,3 +1,4 @@
+THIS_FILE = $(MAKEFILE_LIST)
 # settings.mk is not under source control. Put variables into this
 # file to avoid having to adding the to the make command line.
 -include settings.mk
@@ -549,7 +550,7 @@
 
 UNSET_VARS = for var in $(UNSET_VARIABLES_NAMES); do unset $$var; done
 
-SUB_MAKE = $(MAKE) $(foreach V,$(COMMAND_LINE_ARGS), $(if $($V),$V=$(shell echo "$($V)" | $(FLOW_HOME)/scripts/escape.sh),$V='')) --no-print-directory DESIGN_CONFIG=$(DESIGN_CONFIG)
+SUB_MAKE = $(MAKE) $(foreach V,$(COMMAND_LINE_ARGS), $(if $($V),$V=$(shell echo "$($V)" | $(FLOW_HOME)/scripts/escape.sh),$V='')) --no-print-directory --file=$(THIS_FILE) DESIGN_CONFIG=$(DESIGN_CONFIG)
 UNSET_AND_MAKE = @bash -c '$(UNSET_VARS); $(SUB_MAKE) $$@' --
 
 $(OBJECTS_DIR)/copyright.txt:
