#! /bin/sh
set -e

# A deployed tree is one where FLOW_HOME arrives from the template rather
# than from the build's environment; that is where the stage-target guard
# at the bottom applies.
if [ -z "$FLOW_HOME" ]; then
  _deployed=1
  export MAKE_PATH="${MAKE_PATH}"
  # Yosys-stage runners pass yosys_substitutions(ctx) and get a concrete
  # ${YOSYS_PATH} substituted in. Openroad-stage runners (orfs_final etc.)
  # use only flow_substitutions(ctx) and leave ${YOSYS_PATH} as a literal,
  # which the shell then expands to empty. Only export YOSYS_EXE when
  # we actually got a path; otherwise fall back to the caller's env so
  # `bazel run :_final -- SYNTH_NETLIST_FILES=...` (used by
  # //:make-yosys-netlist for re-synth) can supply yosys via YOSYS_EXE
  # from the user shell.
  if [ -n "${YOSYS_PATH}" ]; then
    export YOSYS_EXE="${YOSYS_PATH}"
  fi
  # A caller-supplied OPENROAD_EXE wins. Pointing a deployed reproducer at
  # a locally built openroad is what the _deps tarball is for, and the
  # deployed tree is the one place the binary is not a bazel label.
  if [ -n "${OPENROAD_EXE:-}" ]; then
    _openroad_exe="$OPENROAD_EXE"
  else
    # Select the Qt-linked openroad only when the caller asked for a
    # gui_* make target. Build-time stages and the portable tarball
    # invoke CLI make targets and therefore keep ${OPENROAD_PATH}.
    _openroad_exe="${OPENROAD_PATH}"
    for _arg in "$@"; do
      case "$_arg" in
        gui_*|gui-*) _openroad_exe="${OPENROAD_QT_PATH}"; break ;;
      esac
    done
  fi
  export OPENROAD_EXE="$_openroad_exe"
  export OPENSTA_EXE="${OPENSTA_PATH}"
  export KLAYOUT_CMD="${KLAYOUT_PATH}"
  export STDBUF_CMD="${STDBUF_PATH}"
  export FLOW_HOME="${FLOW_HOME}"
else
  _deployed=
  # if make is not in the path, error out, otherwise set MAKE_PATH
  if ! command -v make >/dev/null; then
    echo "Error: make is not in the PATH"
    exit 1
  fi
  export MAKE_PATH="$(command -v make)"
fi

# https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/3907
export LEC_CHECK=0

# Default to offscreen Qt platform when no display server is available.
if [ -z "${DISPLAY:-}" ] && [ -z "${WAYLAND_DISPLAY:-}" ]; then
  export QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-offscreen}"
fi

# A deployed tree holds one stage's inputs exactly as bazel built them. A
# bare stage target lets ORFS's dependency chain decide that an upstream
# result is stale and rebuild it here, from inputs bazel never gave the
# tree, and what the tree runs stops matching what the build produced.
# The honest targets are the `do-` ones, which run that stage and nothing
# else; `run`, `open_*` and `gui_*` pass. Stop before make does.
#
# `for _arg do` and not `for _arg in "$@"`: the rules substitute the
# literal "$@" in this template to inject DESIGN_CONFIG, so spelling it
# here would put that assignment into the loop's word list.
if [ -n "$_deployed" ]; then
  _stages="do-yosys, do-floorplan, do-place, do-cts, do-grt, do-route, do-final"
  for _arg do
    case "$_arg" in
      # ORFS spells the synthesis step do-yosys; there is no do-synth.
      synth) _why="rebuild"; _hint="Run one stage: ./make do-yosys" ;;
      floorplan|place|cts|grt|route|final|generate_abstract)
        _why="rebuild"; _hint="Run one stage: ./make do-$_arg" ;;
      # `all` chains every stage, and `clean_all` deletes what bazel
      # staged here; neither has a single-stage form.
      all) _why="rebuild"; _hint="Run one stage at a time: ./make $_stages" ;;
      clean_all)
        _why="delete"
        _hint="Re-deploy the _deps tree instead." ;;
      *) continue ;;
    esac
    if [ "$_why" = "delete" ]; then
      echo "make: refusing target '$_arg' in a deployed tree: it deletes results" >&2
      echo "      bazel staged here, which this tree cannot rebuild." >&2
    else
      echo "make: refusing target '$_arg' in a deployed tree: it would rebuild" >&2
      echo "      upstream stages from inputs bazel never gave this tree." >&2
    fi
    echo "      $_hint" >&2
    exit 2
  done
fi

# A deployed tree is one stage's tree, and it may run that stage only.
#
# The fence, so it is not relitigated: bazel scopes each stage's config.mk
# to the variables of that stage, because config.mk is an input of the
# stage's action and so part of its cache key; a CTS knob must not re-run
# the floorplan. The deployed tree ships that same stage-scoped config, so
# `do-place` in a floorplan tree runs the place stage with ORFS defaults
# for every place variable the design set (ENABLE_DPO, DETAIL_PLACEMENT_ARGS,
# ...), silently, and the output does not match the design. Shipping the
# union of all stages' variables instead is not the fix: a stage's config is
# built from the previous stage's OrfsInfo argument set plus its own
# orfs_arguments, and an orfs_arguments target can be generated by an
# action from an earlier stage's outputs, so a later stage's variables exist
# only after the earlier stages have run in bazel. A union taken at deploy
# time carries the static ones and drops the generated ones without a word.
# It would work for a simple flow and fail in exactly the complicated flows
# where the shortcut is most tempting. Iterate a stage in that stage's own
# `_deps` tree. ORFS_DEPLOY_ANY_STAGE=1 runs the target anyway, for the
# caller who supplies the later stage's variables by hand, and says so.
#
# The stage a `do-` target belongs to; empty for a target that is not one
# stage's (run, open_*, gui_*, ...), which passes.
_stage_of_target() {
  case "$1" in
    do-1_3_floorplan_to_place) echo floorplan ;;
    do-synth|do-yosys*|do-1_*) echo synth ;;
    do-floorplan|do-2_*) echo floorplan ;;
    do-place|do-3_*) echo place ;;
    do-cts|do-4_*) echo cts ;;
    do-grt|do-5_1_*) echo grt ;;
    do-route|do-5_2_*|do-5_3_*) echo route ;;
    do-final|do-6_*|do-gds*) echo final ;;
    do-generate_abstract|do-7_*) echo abstract ;;
  esac
}
_deploy_stage="${DEPLOY_STAGE}"
# 6_gds is the final stage's tree as far as its targets go.
[ "$_deploy_stage" = "gds" ] && _deploy_stage=final
if [ -n "$_deployed" ] && [ -n "$_deploy_stage" ]; then
  for _arg do
    _target_stage=$(_stage_of_target "$_arg")
    [ -n "$_target_stage" ] || continue
    [ "$_target_stage" = "$_deploy_stage" ] && continue
    if [ "${ORFS_DEPLOY_ANY_STAGE:-0}" = "1" ]; then
      echo "make: WARNING: '$_arg' is not a $_deploy_stage target; this tree (${DEPLOY_LABEL}) was deployed for the $_deploy_stage stage" >&2
      echo "      and carries only its variables. ORFS_DEPLOY_ANY_STAGE=1: running it with the later stage's variables you supply." >&2
    else
      echo "make: refusing '$_arg': this tree (${DEPLOY_LABEL}) was deployed for the $_deploy_stage stage and carries" >&2
      echo "      only that stage's variables. A later stage's variables are produced by the stages before it and" >&2
      echo "      exist only in that stage's own deploy tree:" >&2
      echo "        bazelisk run <flow>_<stage>_deps -- --install <dir>    (the _deps target of the stage you want, same flow)" >&2
      echo "      ORFS_DEPLOY_ANY_STAGE=1 runs it here anyway, with the later stage's variables supplied by you." >&2
      exit 2
    fi
  done
fi
exec $MAKE_PATH --file "$FLOW_HOME/Makefile" "$@"
