#!/bin/bash
set -ex
ORFS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ~/orfs_path.sh
export FLOW_HOME=$ORFS/flow
export MAKEFILES=$FLOW_HOME/Makefile

source $ORFS/env.sh

export BAZEL_ORFS=$ORFS_DIR
"$@"
