#!/bin/bash
set -ex
WORKSPACE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ -z $FLOW_HOME ]]; then
    echo>&2 "Missing \`FLOW_HOME\` variable, please source \`env.sh\` file from OpenROAD-flow-scripts or set it manually to OpenROAD-flow-scripts/flow localization"
    exit 1
fi
echo "Using OpenROAD-flow-scripts/flow from $FLOW_HOME"
export MAKEFILES=$FLOW_HOME/Makefile

if [[ $WORKSPACE = * ]]
then
    export BUILD_DIR=$(echo $WORKSPACE | sed 's|external/bazel-orfs~override|execroot/_main|')
else
    export BUILD_DIR=$WORKSPACE
fi

export WORK_HOME=$BUILD_DIR/$RULEDIR

# Make bazel-bin writable
chmod -R +w $WORK_HOME

source $(dirname $FLOW_HOME)/env.sh

"$@"
