"""Where the ORFS tarball comes from, and what bazel-orfs does to it.

ORFS is consumed as an `http_archive` created by the `orfs_repositories`
module extension, not as a `bazel_dep`. The reason is a bzlmod rule:
`patches` on `archive_override`/`git_override` is honoured **only from
the root module**. So while ORFS is a module dependency, the patching
lands on whoever happens to be root -- OpenROAD would have to carry ORFS
patches, and bazel-orfs, as a non-root module, could not patch ORFS at
all.

Module extensions run for every build regardless of which module
declared them, so a repository created here is patched by bazel-orfs's
code either way. A root module picks the *version* with

    orfs = use_extension("@bazel-orfs//:extension.bzl", "orfs_repositories")
    orfs.source(commit = "...", integrity = "sha256-...")

and carries no patches, no strip_prefix and no URL construction.

See docs/plans/orfs-as-file-store.md for the full design.
"""

ORFS_URL_TEMPLATE = "https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/archive/{}.tar.gz"

ORFS_STRIP_PREFIX_TEMPLATE = "OpenROAD-flow-scripts-{}"

# Platforms parsed into DESIGNS, and therefore the only platforms whose
# designs can have flow targets. Must match the `platforms` list passed
# to orfs_designs(). Generating a BUILD under a platform outside this
# list -- gf12 or gt2n, which ORFS exposes no BUILD files for at all --
# invents a package whose design() call DESIGNS cannot resolve.
ORFS_BAZEL_PLATFORMS = [
    "asap7",
    "gf180",
    "ihp-sg13g2",
    "nangate45",
    "sky130hd",
    "sky130hs",
]

ORFS_PATCHES = [
    Label("//patches:0037-orfs-single-writer-1_synth-sdc.patch"),
    Label("//patches:0039-orfs-slang-plugin-fallback.patch"),
    # The config.mk BUILD DSL (design(), files()) lives here, in
    # private/design_dsl.bzl, bound to this consumer's DESIGNS by the
    # generated @orfs_designs//:designs.bzl. ORFS keeps a re-export for
    # the BUILD files it still ships, so those are untouched.
    #
    # Owning the DSL keeps it in step with the rules it drives. It had
    # drifted: ORFS passed a `blender` argument for some time after
    # bazel-orfs removed the parameter, so every @orfs design package
    # failed to load with
    #   Error: orfs_design() got unexpected keyword argument: blender
    # The CI step that loads every @orfs design package guards against a
    # repeat.
    Label("//patches:0046-orfs-design-dsl-reexport.patch"),
]

# Generate the BUILD file for any design directory that has a config.mk
# and no BUILD, so ORFS need not carry ~56 identical
# `design(config = "config.mk")` files whose only reader is bazel -- a
# build system ORFS does not itself use. See docs/orfs-design-builds.md
# for the ORFS-side cleanup this enables.
#
# config.mk only, deliberately. The other ~89 design BUILDs declare a
# files() group -- "verilog", "include", "lef", "lib", "gds" -- and which
# group a directory needs is NOT derivable from its contents:
#
#   * src/cva6 and src/mempool_group/rtl/axi declare files("verilog")
#     while holding no .v/.sv at all (only .svh, or nothing). The
#     filegroup is legitimately empty -- files() globs with allow_empty
#     -- but the label still has to exist, because another design's
#     config.mk references it.
#   * ibex_sv/vendor/.../prim/rtl holds both .sv and .svh and declares
#     files("include"), not files("verilog").
#
# The group is decided by what other configs reference, which lives in
# the config.mk corpus rather than in the directory. Guessing it wrong
# renames a target and breaks those references at the far end.
# test/orfs_design_builds_test.py holds this line: it compares the rules
# below against every canonical BUILD ORFS still ships.
#
# Absent only, never overwritten. That is the safety argument: a design
# with a hand-written BUILD keeps it by virtue of having one, so there is
# no keep-list to maintain and nothing is silently clobbered. It also
# makes this both forward- and backward-compatible: against today's ORFS
# every BUILD exists and this is a no-op, and after the cleanup the
# deleted ones come back identical.
#
# The generated file loads from @orfs_designs//:designs.bzl rather than
# //flow/designs:design.bzl so it does not depend on ORFS keeping the
# re-export.
#
# Drift here is caught by the "Load @orfs design packages" CI step.
_GENERATE_DESIGN_BUILDS = """
for platform in {platforms}; do
  [ -d "flow/designs/$platform" ] || continue
  for d in flow/designs/$platform/*; do
    [ -d "$d" ] || continue
    if [ -e "$d/BUILD" ] || [ -e "$d/BUILD.bazel" ]; then continue; fi
    [ -e "$d/config.mk" ] || continue
    {{
      echo '# Generated by bazel-orfs: see orfs_source.bzl.'
      echo 'load("@orfs_designs//:designs.bzl", "design")'
      echo ''
      echo 'design(config = "config.mk")'
    }} > "$d/BUILD"
  done
done
"""

ORFS_PATCH_CMDS = [
    _GENERATE_DESIGN_BUILDS.format(
        platforms = " ".join(ORFS_BAZEL_PLATFORMS),
    ),
]

def orfs_archive_args(commit, integrity):
    """http_archive arguments for an ORFS commit.

    Args:
      commit: the ORFS commit to fetch.
      integrity: Subresource Integrity string for the tarball.

    Returns:
      A dict of http_archive keyword arguments.
    """
    return {
        "integrity": integrity,
        "patch_args": ["-p1"],
        "patch_cmds": ORFS_PATCH_CMDS,
        "patches": ORFS_PATCHES,
        "strip_prefix": ORFS_STRIP_PREFIX_TEMPLATE.format(commit),
        "urls": [ORFS_URL_TEMPLATE.format(commit)],
    }
