#!/usr/bin/env python3
"""Record the ORFS design BUILD files bazel-orfs cannot generate.

Most design packages are two lines -- `design(config = "config.mk")` --
and orfs_source.bzl generates those for any directory with a config.mk
and no BUILD. The rest cannot be generated, because a `files()` group
name is not derivable from the directory it sits in: it is decided by
which label *other* designs' config.mk files reference. src/cva6
declares files("verilog") while holding no .v or .sv at all, and prim/rtl
holds both .sv and .svh but declares files("include"). Guessing renames
a target and the breakage surfaces in an unrelated design's config.

So these are *recorded* rather than derived: copied verbatim out of ORFS
into orfs_design_builds.bzl, and written back absent-only when ORFS no
longer ships them. That is the difference between carrying data and
guessing it.

Usage:
    ./record_orfs_builds.py <path-to-orfs> > orfs_design_builds.bzl
"""

import os
import subprocess
import sys

# The heredoc delimiter the writer uses. No recorded file may contain it.
DELIMITER = "ORFS_RECORDED_BUILD_EOF"

# Generated for any directory with a config.mk and no BUILD, so recording
# them too would be duplication with two sources of truth.
GENERATED_BODY = (
    'load("//flow/designs:design.bzl", "design")',
    'design(config = "config.mk")',
)


def is_generated(text):
    """True if orfs_source.bzl's generator would produce this file."""
    lines = [
        l.strip()
        for l in text.splitlines()
        if l.strip() and not l.strip().startswith("#")
    ]
    return tuple(lines) == GENERATED_BODY


def collect(root):
    found = {}
    designs = os.path.join(root, "flow", "designs")
    for dirpath, _, filenames in os.walk(designs):
        for name in ("BUILD", "BUILD.bazel"):
            if name not in filenames:
                continue
            path = os.path.join(dirpath, name)
            with open(path, encoding="utf-8") as fp:
                text = fp.read()
            if is_generated(text):
                continue
            rel = os.path.relpath(path, root)
            if DELIMITER in text:
                raise SystemExit("%s contains the heredoc delimiter" % rel)
            found[rel] = text
    return found


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    root = sys.argv[1]

    # Refuse a dirty tree. Recording from one silently captures local
    # edits: a first run against a campaign branch recorded 119 files
    # instead of 117, the two extras being uncommitted config.mk work.
    dirty = subprocess.run(
        ["git", "-C", root, "status", "--porcelain", "--", "flow/designs"],
        capture_output=True,
        text=True,
    ).stdout.strip()
    if dirty:
        raise SystemExit(
            "flow/designs has local changes in %s; record from a clean "
            "checkout:\n%s" % (root, dirty)
        )

    found = collect(root)
    commit = subprocess.run(
        ["git", "-C", root, "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
    ).stdout.strip()

    out = sys.stdout
    out.write('"""ORFS design BUILD files recorded verbatim.\n\n')
    out.write("Generated by ./record_orfs_builds.py -- do not hand-edit.\n")
    out.write("Recorded from ORFS %s: %d files.\n\n" % (commit, len(found)))
    out.write("These are the design packages orfs_source.bzl cannot generate,\n")
    out.write("because a files() group name is decided by what other designs'\n")
    out.write("config.mk files reference rather than by the directory's contents.\n")
    out.write("Written back absent-only, so this is a no-op against an ORFS that\n")
    out.write("still ships them.\n")
    out.write('"""\n\n')
    # Emit what buildifier would emit, so `//:fix_lint` is a no-op on
    # this file and CI's `git diff --exit-code` stays clean. buildifier
    # prefers double quotes, except where the content itself contains a
    # double quote -- which every recorded BUILD does.
    out.write('RECORDED_FROM_ORFS = "%s"\n\n' % commit)
    out.write("RECORDED_BUILDS = {\n")
    for rel in sorted(found):
        out.write('    "%s": %r,\n' % (rel, found[rel]))
    out.write("}\n")


if __name__ == "__main__":
    main()
