#!/usr/bin/env python3
"""Unit tests for rtlil_kept_modules.py"""

import json
import os
import tempfile
import unittest

from rtlil_kept_modules import extract_kept_modules

SAMPLE_RTLIL = """\
# Generated by Yosys
autoidx 100
attribute \\blackbox 1
attribute \\area "56.435"
module \\sky130_fd_sc_hd__nand2_1
end
attribute \\src "top.v:1"
module \\small_mod
  wire \\a
end
attribute \\src "top.v:100"
attribute \\keep_hierarchy 1
module \\big_mod_a
  wire \\x
  cell \\nand2 \\u1
  end
end
attribute \\src "top.v:200"
module \\not_kept
  wire \\y
end
attribute \\keep_hierarchy 1
attribute \\src "top.v:300"
module \\big_mod_b
  wire \\z
end
module \\also_not_kept
end
"""


class TestExtractKeptModules(unittest.TestCase):
    def test_basic(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".rtlil", delete=False) as f:
            f.write(SAMPLE_RTLIL)
            f.flush()
            try:
                result = extract_kept_modules(f.name)
            finally:
                os.unlink(f.name)
        self.assertEqual(result, ["big_mod_a", "big_mod_b"])

    def test_top_is_excluded_when_named(self):
        # yosys's keep_hierarchy marks the top like any other module. For
        # partitioning the top is not a kept submodule -- the top partition
        # synthesizes it with the kept modules blackboxed -- so with the
        # top in the list a regular partition synthesized it too and the
        # top partition blackboxed itself (asap7/riscv32i, discovery mode).
        with tempfile.NamedTemporaryFile(mode="w", suffix=".rtlil", delete=False) as f:
            f.write(SAMPLE_RTLIL)
            f.flush()
            try:
                result = extract_kept_modules(f.name, top="big_mod_a")
                unnamed = extract_kept_modules(f.name, top="not_in_design")
            finally:
                os.unlink(f.name)
        self.assertEqual(result, ["big_mod_b"])
        self.assertEqual(unnamed, ["big_mod_a", "big_mod_b"])

    def test_empty(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".rtlil", delete=False) as f:
            f.write("# empty\nmodule \\top\nend\n")
            f.flush()
            try:
                result = extract_kept_modules(f.name)
            finally:
                os.unlink(f.name)
        self.assertEqual(result, [])

    def test_real_rtlil(self):
        """Test against the actual swerv_wrapper keep RTLIL if available."""
        path = (
            "bazel-bin/flow/designs/asap7/swerv_wrapper/"
            "results/asap7/swerv_wrapper/base/1_1_yosys_keep.rtlil"
        )
        if not os.path.exists(path):
            self.skipTest(f"{path} not found")
        result = extract_kept_modules(path)
        self.assertGreater(len(result), 10)
        self.assertIn("dec_tlu_ctl", result)
        self.assertIn("exu", result)
        # No liberty/blackbox modules should be in the list
        for m in result:
            self.assertFalse(m.startswith("sky130"))
            self.assertFalse(m.startswith("asap7"))


if __name__ == "__main__":
    unittest.main()
