# Generated by plan_floorplan.py: every signal pin of Frontend on its bottom
# side, the side that faces the parent's logic region when the parent
# places the block R0 on the region's top.
set names {}
foreach bterm [[ord::get_db_block] getBTerms] {
  if { [$bterm getSigType] ne "SIGNAL" && [$bterm getSigType] ne "CLOCK" } { continue }
  lappend names [$bterm getName]
}
set_io_pin_constraint -region bottom:* -pin_names $names
puts "Frontend_pins.tcl: [llength $names] pins on bottom"
