# Generated by plan_floorplan.py: every signal pin of MemBlock on its top
# side, the side that faces the parent's logic region when the parent
# places the block R0 on the region's bottom.
set names {}
foreach bterm [[ord::get_db_block] getBTerms] {
  if { [$bterm getSigType] ne "SIGNAL" && [$bterm getSigType] ne "CLOCK" } { continue }
  lappend names [$bterm getName]
}
set_io_pin_constraint -region top:* -pin_names $names
puts "MemBlock_pins.tcl: [llength $names] pins on top"
