# Generated by plan_floorplan.py: the planned floorplan, each block found
# by its master and placed R0 with -exact (mpl's snapper would move the
# origin off the pin lattice the plan put it on).
set block [ord::get_db_block]
foreach {master x y} {
  MemBlock 60.768 10.800
  Region_1 1067.328 397.440
  Frontend 10.080 2620.080
  VecRegionModule 975.600 2676.240
} {
  set insts {}
  foreach inst [$block getInsts] {
    if { [[$inst getMaster] getName] eq $master } { lappend insts $inst }
  }
  if { [llength $insts] != 1 } {
    utl::error FLW 1 "plan: $master has [llength $insts] instances, the plan places one"
  }
  place_macro -macro_name [[lindex $insts 0] getName] -location [list $x $y] -orientation R0 -exact
  puts "place_macros.tcl: $master at $x $y um, R0"
}
