# Generated by plan_floorplan.py: the planned floorplan, each block found
# by its master and placed R0 with -exact (mpl's snapper would move the
# origin off the pin lattice the plan put it on).
set block [ord::get_db_block]
foreach {master x y} {
  Frontend 10.224 101.520
  MemBlock 1024.992 32.400
  VecRegionModule 2080.656 233.280
  Region_1 2948.544 390.960
} {
  set insts {}
  foreach inst [$block getInsts] {
    if { [[$inst getMaster] getName] eq $master } { lappend insts $inst }
  }
  if { [llength $insts] != 1 } {
    utl::error FLW 1 "plan: $master has [llength $insts] instances, the plan places one"
  }
  place_macro -macro_name [[lindex $insts 0] getName] -location [list $x $y] -orientation R0 -exact
  [lindex $insts 0] setPlacementStatus FIRM
  puts "place_macros.tcl: $master at $x $y um, R0"
}
# The band the blocks occupy is the blocks' and the wires': a soft
# placement blockage over it, from the lowest block bottom to the lowest
# block top of the row (mirrored for a top row). Global placement blocks
# the sites of every blockage, soft or not, so no parent cell is seeded in
# a pocket under a shorter block or in a channel between two, where its
# wires would have to leave through the channel (XiangShan take 23: 7
# percent of the route-0 overflow). The detailed placer skips soft
# blockages (dbToOpendp.cpp), so the rows stay legal underneath, and the
# few hundred buffers repair_design puts there afterwards -- it respects
# neither rows nor blockages -- have a site under them. A hard blockage,
# or removing the rows, strands those buffers instead: the negotiation
# legaliser's initialSnap then relocates each by an expanding ring search
# whose cost grows with the distance, and the stage does not return
# (inventory entry 21).
set dbu [[ord::get_db_tech] getDbUnitsPerMicron]
set core [$block getCoreArea]
set bands 0
foreach {lo hi} {
  32.400 1028.160
} {
  set bl [odb::dbBlockage_create $block [$core xMin] [expr { int($lo * $dbu) }] [$core xMax] [expr { int($hi * $dbu) }]]
  $bl setSoft
  incr bands
}
puts "place_macros.tcl: $bands soft placement blockage(s) over the blocks' bands; the rows stay"
# Macros the plan does not name (the parent's own generated register files
# and memories) go around the planned blocks, which are FIRM and stay put.
set rest {}
foreach inst [$block getInsts] {
  if { [[$inst getMaster] isBlock] && ![$inst isFixed] } { lappend rest [$inst getName] }
}
if { [llength $rest] > 0 } {
  puts "place_macros.tcl: [llength $rest] macros not in the plan; rtl_macro_placer places them around the planned blocks"
  rtl_macro_placer -halo_width 2 -halo_height 2
}
