"""Generated by plan_floorplan.py from the macro selection tables; do not edit."""

PLAN = {
    "macros": {
        "CoupledL2": {
            "CORE_AREA": "10.000 10.000 851.840 851.840",
            "DIE_AREA": "0.000 0.000 861.840 861.840",
            "SYNTH_KEEP_MODULES": "MSHRCtl Slice VpnTable MainPipe_1 RequestArb SentUnit RequestBuffer TwoLevelRRArbiter_22 FtTrainPipeline SinkC MMIOBridge CDPPrefetcher Directory OffsetScoreTable_1 TwoLevelRRArbiter_16 MSHR OverwriteQueue_1",
            "pin_side": "top",
            "x_um": 1504.944,
            "y_um": 41.04,
        },
        "FltRegionModule": {
            "CORE_AREA": "10.000 10.000 655.280 655.280",
            "DIE_AREA": "0.000 0.000 665.280 665.280",
            "SYNTH_KEEP_MODULES": "FMulFlt FDivSqrtFlt IssuePipeFaluFmulFcvtFcmp IssuePipeFaluFmulFdiv IssuePipeFaluFmulFdiv_1 IssuePipeFaluFmul IssueQueueFaluFmulFcvtFcmp IssueQueueFaluFmulFdiv IssueQueueFaluFmulFdiv_1 IssueQueueFaluFmul",
            "pin_side": "top",
            "x_um": 10.224,
            "y_um": 203.04,
        },
        "Frontend": {
            "CORE_AREA": "10.000 10.000 944.720 944.720",
            "DIE_AREA": "0.000 0.000 954.720 954.720",
            "SYNTH_KEEP_MODULES": "Ifu ResolveQueue ICache Phr Bpu Sc TLB IBuffer AheadBtb Ittage Tage MicroTage PMP WriteBuffer_4 Ftq PMPChecker",
            "pin_side": "bottom",
            "x_um": 206.784,
            "y_um": 1946.16,
        },
        "MemBlock": {
            "CORE_AREA": "10.000 10.000 987.920 987.920",
            "DIE_AREA": "0.000 0.000 997.920 997.920",
            "SYNTH_KEEP_MODULES": "LoadQueueReplay PrefetcherWrapper Sbuffer PtwCache DCacheWrapper TLBNonBlock MissQueue LoadQueueUncache SbufferData TLBNonBlock_2 TLBNonBlock_1 SqForwardPipe L2TLBWrapper VirtualStoreQueue LoadQueueRAR HPerfMonitor_3 LoadQueueRAW PhysicalStoreQueue Uncache L1PrefetchSourceArray BankedDataArray MainPipe PTWNewFilter VirtualLoadQueue L1ErrorMetaArray L1CohMetaArray LLPTW",
            "pin_side": "bottom",
            "x_um": 1172.304,
            "y_um": 2013.12,
        },
        "VecRegionModule": {
            "CORE_AREA": "10.000 10.000 797.840 797.840",
            "DIE_AREA": "0.000 0.000 807.840 807.840",
            "SYNTH_KEEP_MODULES": "VFDivWrapper VIDiv VIMacU IssuePipeVialuVimacVmoveVfcvtVfmac IssuePipeVialuVidivVfmacVfdiv IssuePipeVialu IssuePipeVialu_1 VectorCvt IssueQueueVialuVimacVmoveVfcvtVfmac IssueQueueVialu IssueQueueVialu_1 IssueQueueVialuVidivVfmacVfdiv VFMacWrapper",
            "pin_side": "top",
            "x_um": 686.304,
            "y_um": 32.4,
        },
    },
    "parent": {
        "CORE_AREA": "10.000 10.000 2366.928 3032.962",
        "DIE_AREA": "0.000 0.000 2376.928 3042.962",
        "SYNTH_KEEP_MODULES": "Backend CtrlBlock FusionDecoder Region DecodeStage SimpleDecodeChannel UopBufferCtrlDecoder Rob Dispatch Rename MemCtrl IssueQueueAluCsrFenceLinkBrhNjmp IssueQueueAluDivBrhNjmp IssueQueueAluI2fBrhNjmp IssueQueueAluBkuVset IssueQueueAluMul IssueQueueLdu IssueQueueStaMou IssueQueueStaMou_1 IssueQueueStdMoud IssueQueueStdMoud_1 DataPath ExuBlock VectorDecodeChannel RenameBuffer VTypeBuffer RobEntryCell BusyTable BusyTable_1 RenameTableWrapper CompressUnit SSIT LFST EntriesAluCsrFenceLinkBrhNjmp EntriesAluDivBrhNjmp EntriesAluI2fBrhNjmp EntriesAluBkuVset EntriesAluMul EntriesLdu EntriesStaMou EntriesStdMoud ExeUnitImp NewCSR Frontend MemBlock VecRegionModule FltRegionModule XSCore L2Top",
        "netlists": [
            {
                "h_um": 192.51,
                "instance": "core/backend/inner_ctrlBlock/rob/robEntryFile",
                "module": "RobEntryFile",
                "w_um": 318.384,
                "x_um": 20.944,
                "y_um": 1701.619,
            },
            {
                "h_um": 243.0,
                "instance": "core/backend/inner_intRegion/intDataPath/intRegFile",
                "module": "IntRegFile",
                "w_um": 406.0,
                "x_um": 350.128,
                "y_um": 1651.129,
            },
            {
                "h_um": 192.24,
                "instance": "core/backend/inner_ctrlBlock/rob/rab/renameBuffer",
                "module": "RenameBufferFile",
                "w_um": 306.504,
                "x_um": 766.928,
                "y_um": 1701.889,
            },
        ],
    },
}
