# Generated by plan_floorplan.py: every signal port of the parent on its
# bottom edge, the one facing what it plugs into; the blocks with port
# partners sit on that side with their port pins on their outer side.
set names {}
foreach bterm [[ord::get_db_block] getBTerms] {
  if { [$bterm getSigType] ne "SIGNAL" && [$bterm getSigType] ne "CLOCK" } { continue }
  lappend names [$bterm getName]
}
set_io_pin_constraint -region bottom:* -pin_names $names
puts "parent_pins.tcl: [llength $names] ports on the bottom edge"
