# Generated by plan_floorplan.py: the planned floorplan, each block found
# by its master and placed R0 with -exact (mpl's snapper would move the
# origin off the pin lattice the plan put it on).
set block [ord::get_db_block]
foreach {master x y} {
  BlockA 14.544 12.960
  BlockD 79.344 15.120
  BlockB 10.224 170.640
  BlockC 83.664 170.640
} {
  set insts {}
  foreach inst [$block getInsts] {
    if { [[$inst getMaster] getName] eq $master } { lappend insts $inst }
  }
  if { [llength $insts] != 1 } {
    utl::error FLW 1 "plan: $master has [llength $insts] instances, the plan places one"
  }
  place_macro -macro_name [[lindex $insts 0] getName] -location [list $x $y] -orientation R0 -exact
  [lindex $insts 0] setPlacementStatus FIRM
  puts "place_macros.tcl: $master at $x $y um, R0"
}
# The band the blocks occupy is theirs alone: below the lowest top of the
# bottom row (and above the highest bottom of a top row) the rows are
# removed, so no parent cell lands in the pockets under a shorter block
# or in the channels between blocks, reachable only through a channel
# (XiangShan take 23: 7 percent of the route-0 overflow sat there). The
# blocks' own outlines cut the rows in any case; this cuts the rest of
# the band. Rows are removed rather than blocked: a placement blockage
# still gets tapcells and edge cells, which the legaliser's row check
# then fails (place_block_lateral.tcl).
set dbu [[ord::get_db_tech] getDbUnitsPerMicron]
set cut 0
foreach {lo hi} {
  0.000 66.960
  170.640 245.440
} {
  set lo [expr { int($lo * $dbu) }]
  set hi [expr { int($hi * $dbu) }]
  foreach row [$block getRows] {
    set bb [$row getBBox]
    if { [$bb yMin] >= $lo && [$bb yMax] <= $hi } { odb::dbRow_destroy $row; incr cut }
  }
}
puts "place_macros.tcl: $cut rows removed from the blocks' bands"
# Macros the plan does not name (the parent's own generated register files
# and memories) go around the planned blocks, which are FIRM and stay put.
set rest {}
foreach inst [$block getInsts] {
  if { [[$inst getMaster] isBlock] && ![$inst isFixed] } { lappend rest [$inst getName] }
}
if { [llength $rest] > 0 } {
  puts "place_macros.tcl: [llength $rest] macros not in the plan; rtl_macro_placer places them around the planned blocks"
  rtl_macro_placer -halo_width 2 -halo_height 2
}
