# Generated by plan_floorplan.py: the planned floorplan, each block found
# by its master and placed R0 with -exact (mpl's snapper would move the
# origin off the pin lattice the plan put it on).
set block [ord::get_db_block]
foreach {master x y} {
  BlockA 14.544 32.400
  BlockD 79.344 34.560
  BlockB 10.224 190.080
  BlockC 83.664 190.080
} {
  set insts {}
  foreach inst [$block getInsts] {
    if { [[$inst getMaster] getName] eq $master } { lappend insts $inst }
  }
  if { [llength $insts] != 1 } {
    utl::error FLW 1 "plan: $master has [llength $insts] instances, the plan places one"
  }
  place_macro -macro_name [[lindex $insts 0] getName] -location [list $x $y] -orientation R0 -exact
  [lindex $insts 0] setPlacementStatus FIRM
  puts "place_macros.tcl: $master at $x $y um, R0"
}
# The band the blocks occupy is the blocks' and the wires': a soft
# placement blockage over it, from the lowest block bottom to the lowest
# block top of the row (mirrored for a top row). Global placement blocks
# the sites of every blockage, soft or not, so no parent cell is seeded in
# a pocket under a shorter block or in a channel between two, where its
# wires would have to leave through the channel (XiangShan take 23: 7
# percent of the route-0 overflow). The detailed placer skips soft
# blockages (dbToOpendp.cpp), so the rows stay legal underneath, and the
# few hundred buffers repair_design puts there afterwards -- it respects
# neither rows nor blockages -- have a site under them. A hard blockage,
# or removing the rows, strands those buffers instead: the negotiation
# legaliser's initialSnap then relocates each by an expanding ring search
# whose cost grows with the distance, and the stage does not return
# (inventory entry 21).
set dbu [[ord::get_db_tech] getDbUnitsPerMicron]
set core [$block getCoreArea]
set bands 0
foreach {lo hi} {
  32.400 86.400
  190.080 252.720
} {
  set bl [odb::dbBlockage_create $block [$core xMin] [expr { int($lo * $dbu) }] [$core xMax] [expr { int($hi * $dbu) }]]
  $bl setSoft
  incr bands
}
puts "place_macros.tcl: $bands soft placement blockage(s) over the blocks' bands; the rows stay"
# Macros the plan does not name (the parent's own generated register files
# and memories) go around the planned blocks, which are FIRM and stay put.
set rest {}
foreach inst [$block getInsts] {
  if { [[$inst getMaster] isBlock] && ![$inst isFixed] } { lappend rest [$inst getName] }
}
if { [llength $rest] > 0 } {
  puts "place_macros.tcl: [llength $rest] macros not in the plan; rtl_macro_placer places them around the planned blocks"
  # rtl_macro_placer refuses a FIRM standard cell in its area (MPL-0050),
  # and the plan's placed netlists are FIRM from floorplan on. For the
  # macro step only they are PLACED, and a hard placement blockage over
  # each netlist's cells, which rtl_macro_placer keeps macros off, stands
  # in for them; after it, both are undone.
  set firm {}
  array set box {}
  foreach inst [$block getInsts] {
    if { [[$inst getMaster] isBlock] || [$inst getPlacementStatus] ne "FIRM" } { continue }
    lappend firm [list $inst [$inst getLocation] [$inst getOrient]]
    set key [file dirname [$inst getName]]
    set b [$inst getBBox]
    if { [info exists box($key)] } {
      lassign $box($key) x0 y0 x1 y1
      set box($key) [list [expr { min($x0, [$b xMin]) }] [expr { min($y0, [$b yMin]) }] [expr { max($x1, [$b xMax]) }] [expr { max($y1, [$b yMax]) }]]
    } else {
      set box($key) [list [$b xMin] [$b yMin] [$b xMax] [$b yMax]]
    }
  }
  set stand_ins {}
  foreach key [array names box] {
    lassign $box($key) x0 y0 x1 y1
    lappend stand_ins [odb::dbBlockage_create $block $x0 $y0 $x1 $y1]
  }
  foreach f $firm { [lindex $f 0] setPlacementStatus PLACED }
  puts "place_macros.tcl: [llength $firm] FIRM netlist cells stand aside for the macro step, [llength $stand_ins] blockage(s) in their place"
  rtl_macro_placer -halo_width 2 -halo_height 2
  # rtl_macro_placer moves a cluster's standard cells to one point: put
  # every netlist cell back where the plan put it
  foreach f $firm {
    lassign $f inst loc orient
    $inst setOrient $orient
    $inst setLocation {*}$loc
    $inst setPlacementStatus FIRM
  }
  foreach bl $stand_ins { odb::dbBlockage_destroy $bl }
}
