"""Generated by plan_floorplan.py from the macro selection tables; do not edit."""

PLAN = {
    "macros": {
        "BlockA": {
            "CORE_AREA": "10.000 10.000 44.000 44.000",
            "DIE_AREA": "0.000 0.000 54.000 54.000",
            "pin_side": "top",
            "x_um": 14.544,
            "y_um": 12.96,
        },
        "BlockB": {
            "CORE_AREA": "10.000 10.000 52.640 52.640",
            "DIE_AREA": "0.000 0.000 62.640 62.640",
            "pin_side": "bottom",
            "x_um": 10.224,
            "y_um": 170.64,
        },
        "BlockC": {
            "CORE_AREA": "10.000 10.000 41.840 41.840",
            "DIE_AREA": "0.000 0.000 51.840 51.840",
            "pin_side": "bottom",
            "x_um": 83.664,
            "y_um": 170.64,
        },
        "BlockD": {
            "CORE_AREA": "10.000 10.000 41.840 41.840",
            "DIE_AREA": "0.000 0.000 51.840 51.840",
            "pin_side": "top",
            "x_um": 79.344,
            "y_um": 15.12,
        }
    },
    "parent": {
        "CORE_AREA": "10.000 10.000 135.648 235.440",
        "DIE_AREA": "0.000 0.000 145.648 245.440",
        "netlists": [
            {
                "h_um": 10.5,
                "instance": "u_filea",
                "module": "FileA",
                "w_um": 30.0,
                "x_um": 20.944,
                "y_um": 128.717,
            },
            {
                "h_um": 10.5,
                "instance": "u_fileb",
                "module": "FileB",
                "w_um": 30.0,
                "x_um": 61.744,
                "y_um": 128.717,
            },
            {
                "h_um": 10.5,
                "instance": "u_filec",
                "module": "FileC",
                "w_um": 30.0,
                "x_um": 20.944,
                "y_um": 107.4,
            }
        ],
    }
}
