"""Generated by plan_floorplan.py from the macro selection tables; do not edit."""

PLAN = {
    "macros": {
        "BlockA": {
            "CORE_AREA": "10.000 10.000 44.000 44.000",
            "DIE_AREA": "0.000 0.000 54.000 54.000",
            "pin_side": "bottom",
            "x_um": 146.304,
            "y_um": 64.8,
        },
        "BlockB": {
            "CORE_AREA": "10.000 10.000 52.640 52.640",
            "DIE_AREA": "0.000 0.000 62.640 62.640",
            "pin_side": "bottom",
            "x_um": 72.864,
            "y_um": 64.8,
        },
        "BlockC": {
            "CORE_AREA": "10.000 10.000 41.840 41.840",
            "DIE_AREA": "0.000 0.000 51.840 51.840",
            "pin_side": "bottom",
            "x_um": 10.224,
            "y_um": 64.8,
        },
        "BlockD": {
            "CORE_AREA": "10.000 10.000 41.840 41.840",
            "DIE_AREA": "0.000 0.000 51.840 51.840",
            "pin_side": "bottom",
            "x_um": 211.104,
            "y_um": 64.8,
        },
    },
    "parent": {
        "CORE_AREA": "10.000 10.000 263.088 149.060",
        "DIE_AREA": "0.000 0.000 273.088 159.060",
        "netlists": [
            {
                "h_um": 10.5,
                "instance": "u_filea",
                "module": "FileA",
                "w_um": 30.0,
                "x_um": 20.944,
                "y_um": 22.96,
            },
            {
                "h_um": 10.5,
                "instance": "u_fileb",
                "module": "FileB",
                "w_um": 30.0,
                "x_um": 61.744,
                "y_um": 22.96,
            },
            {
                "h_um": 10.5,
                "instance": "u_filec",
                "module": "FileC",
                "w_um": 30.0,
                "x_um": 102.544,
                "y_um": 22.96,
            },
        ],
        "pins": "parent_pins.tcl",
    },
}
