"""A testbench comparing a module before and after SYNTH_VERILOG_SURGERY.

The original module (renamed <module>_orig, with the modules it
instantiates) and the surgered one (with its register file as
generate_regfile's netlist) see the same random inputs on the module's
own ports; tb_top reports `mismatch` when any output differs. It drives
tb_main.cc through the same interface as gen_tb.py's benches: clocks
and reset are tb_top's, every other input is a slice of `stim`, and
--tie holds an input at a constant on both sides.

Writes tb_top.v, the two module bundles and the config for tb_main.cc.
"""

import argparse
import re
import sys


def modules(texts):
    """name -> definition text, from every file."""
    defs = {}
    for text in texts:
        for m in re.finditer(r"^module\s+(\w+)\b.*?^endmodule\b", text, re.M | re.S):
            defs.setdefault(m.group(1), m.group(0))
    return defs


def closure(top, defs, stop=()):
    """`top` and every module it instantiates, transitively."""
    out, todo = [], [top]
    while todo:
        m = todo.pop()
        if m in out or m in stop:
            continue
        if m not in defs:
            sys.exit("gen_cmp_tb: no definition of %s" % m)
        out.append(m)
        body = defs[m].split("\n", 1)[1]
        for name in re.findall(
            r"^\s*([A-Za-z_]\w*)\s*(?:#\s*\(.*?\)\s*)?\n?\s*[A-Za-z_\\][\w\\.\[\]]*\s*\(",
            body,
            re.M | re.S,
        ):
            if name in defs and name != m:
                todo.append(name)
    return out


def ports(definition):
    """(direction, width, name) of a non-ANSI or ANSI module header."""
    out = []
    for kind, width, names in re.findall(
        r"^\s*(input|output)\s+(?:wire\s+|logic\s+)?(\[\s*\d+\s*:\s*\d+\s*\])?\s*([^;()]+?)\s*[;,)]?\s*$",
        definition,
        re.M,
    ):
        w = 1
        if width:
            hi, lo = re.findall(r"\d+", width)
            w = abs(int(hi) - int(lo)) + 1
        for n in names.split(","):
            n = n.strip()
            if n:
                out.append((kind, w, n))
    return out


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--module", required=True)
    p.add_argument("--orig", nargs="+", required=True, help="the original sources")
    p.add_argument("--new", nargs="+", required=True, help="the surgered sources")
    p.add_argument("--netlist", required=True, help="generate_regfile's netlist")
    p.add_argument("--regfile-module", required=True)
    p.add_argument("--clock", action="append", required=True)
    p.add_argument("--reset", required=True, help="port:low|high")
    p.add_argument("--tie", action="append", default=[], help="input=value")
    p.add_argument("--tb", required=True)
    p.add_argument("--orig-out", required=True)
    p.add_argument("--new-out", required=True)
    p.add_argument("--config", required=True)
    a = p.parse_args()

    orig = modules(open(f).read() for f in a.orig)
    new = modules(open(f).read() for f in a.new)
    keep_orig = closure(a.module, orig)
    shared = set(keep_orig) - {a.module}
    keep_new = closure(a.module, new, stop=shared | {a.regfile_module})
    with open(a.orig_out, "w") as f:
        for m in keep_orig:
            text = orig[m]
            if m == a.module:
                text = re.sub(
                    r"^module\s+%s\b" % m,
                    "module %s_orig" % m,
                    text,
                    count=1,
                    flags=re.M,
                )
            f.write(text + "\n\n")
    with open(a.new_out, "w") as f:
        for m in keep_new:
            f.write(new[m] + "\n\n")

    io = ports(orig[a.module])
    names = {n for _, _, n in io}
    rname, level = a.reset.split(":")
    ties = dict(t.split("=", 1) for t in a.tie)
    for n in a.clock + [rname] + list(ties):
        if n not in names:
            sys.exit("gen_cmp_tb: %s is not a port of %s" % (n, a.module))
    stim = [
        (w, n)
        for k, w, n in io
        if k == "input" and n not in a.clock and n != rname and n not in ties
    ]
    outs = [(w, n) for k, w, n in io if k == "output"]
    total = sum(w for w, _ in stim)
    stim_w = max(96, (total + 31) // 32 * 32)
    o = ["// generated by gen_cmp_tb.py: %s before and after surgery" % a.module]
    o.append("module tb_top (")
    o.append("    input clk, input rst_act, input init_mode, input [4:0] init_addr,")
    o.append("    input [%d:0] stim, output mismatch);" % (stim_w - 1))
    off = 0
    conns = []
    for w, n in stim:
        o.append("  wire [%d:0] %s = stim[%d:%d];" % (w - 1, n, off + w - 1, off))
        conns.append(".%s(%s)" % (n, n))
        off += w
    conns += [".%s(clk)" % c for c in a.clock]
    conns.append(".%s(%s)" % (rname, "~rst_act" if level == "low" else "rst_act"))
    conns += [".%s(%s)" % (k, v) for k, v in ties.items()]
    for w, n in outs:
        o.append("  wire [%d:0] %s_orig, %s_new;" % (w - 1, n, n))
    o.append(
        "  %s_orig u_orig (%s);"
        % (a.module, ", ".join(conns + [".%s(%s_orig)" % (n, n) for _, n in outs]))
    )
    o.append(
        "  %s u_new (%s);"
        % (a.module, ", ".join(conns + [".%s(%s_new)" % (n, n) for _, n in outs]))
    )
    o.append(
        "  assign mismatch = %s;"
        % " | ".join("(%s_orig != %s_new)" % (n, n) for _, n in outs)
    )
    # The first mismatches, inputs and both sides' outputs, for the log.
    o.append("  int shown = 0;")
    o.append("  always @(posedge clk) if (mismatch && shown < 4) begin")
    o.append("    shown <= shown + 1;")
    o.append(
        '    $display("mismatch: %s", %s);'
        % (
            " ".join("%s=%%h" % n for _, n in stim)
            + " "
            + " ".join("%s=%%h/%%h" % n for _, n in outs),
            ", ".join(
                [n for _, n in stim]
                + [x for _, n in outs for x in (n + "_orig", n + "_new")]
            ),
        )
    )
    o.append("  end")
    o.append("endmodule")
    with open(a.tb, "w") as f:
        f.write("\n".join(o) + "\n")
    with open(a.config, "w") as f:
        f.write("// generated by gen_cmp_tb.py, for tb_main.cc\n")
        f.write("extern const int kWords = 0;\n")
        f.write("extern const int kStimWords = %d;\n" % (stim_w // 32))
        f.write("extern const bool kAsyncReset = true;\n")
        f.write("extern const bool kExpectMismatch = false;\n")


if __name__ == "__main__":
    main()
