filegroup(
    name = "asap7_files",
    srcs = [
        "asap7sc7p5t_AO_RVT_TT_201020.v",
        "asap7sc7p5t_INVBUF_RVT_TT_201020.v",
        "asap7sc7p5t_OA_RVT_TT_201020.v",
        "asap7sc7p5t_SIMPLE_RVT_TT_201020.v",
    ],
    visibility = ["//visibility:public"],
)
