filegroup(
    name = "asap7_files",
    srcs = [
        "asap7sc7p5t_AO_RVT_TT_201020.v",
        "asap7sc7p5t_INVBUF_RVT_TT_201020.v",
        "asap7sc7p5t_OA_RVT_TT_201020.v",
        "asap7sc7p5t_SIMPLE_RVT_TT_201020.v",
        # TODO: dff.v previously came from @docker_orfs. Needs an
        # exports_files patch in @orfs//flow/BUILD.bazel to restore.
    ],
    visibility = ["//visibility:public"],
)
