// A parent of registers around one MainBtbWriteBufferEnq: every input
// launched and every output captured by a flop, so paths through the
// generated cells are register to register.
module dissolve_parent(input clock, input reset, input [71:0] in, output [219:0] out);
  reg [0:0] r_io_writeEntry_valid;
  always @(posedge clock) r_io_writeEntry_valid <= in[0:0];
  reg [7:0] r_io_writeEntry_bits_setIdx;
  always @(posedge clock) r_io_writeEntry_bits_setIdx <= in[8:1];
  reg [3:0] r_io_writeEntry_bits_wayMask;
  always @(posedge clock) r_io_writeEntry_bits_wayMask <= in[12:9];
  reg [15:0] r_io_writeEntry_bits_entry_tag;
  always @(posedge clock) r_io_writeEntry_bits_entry_tag <= in[28:13];
  reg [1:0] r_io_writeEntry_bits_entry_attribute_branchType;
  always @(posedge clock) r_io_writeEntry_bits_entry_attribute_branchType <= in[30:29];
  reg [1:0] r_io_writeEntry_bits_entry_attribute_rasAction;
  always @(posedge clock) r_io_writeEntry_bits_entry_attribute_rasAction <= in[32:31];
  reg [3:0] r_io_writeEntry_bits_entry_position;
  always @(posedge clock) r_io_writeEntry_bits_entry_position <= in[36:33];
  reg [1:0] r_io_writeEntry_bits_entry_targetCarry_value;
  always @(posedge clock) r_io_writeEntry_bits_entry_targetCarry_value <= in[38:37];
  reg [19:0] r_io_writeEntry_bits_entry_targetLowerBits;
  always @(posedge clock) r_io_writeEntry_bits_entry_targetLowerBits <= in[58:39];
  reg [0:0] r_io_flush_valid;
  always @(posedge clock) r_io_flush_valid <= in[59:59];
  reg [7:0] r_io_flush_bits_setIdx;
  always @(posedge clock) r_io_flush_bits_setIdx <= in[67:60];
  reg [3:0] r_io_flush_bits_wayMask;
  always @(posedge clock) r_io_flush_bits_wayMask <= in[71:68];
  wire [0:0] w_io_write_0_valid;
  reg [0:0] q_io_write_0_valid;
  always @(posedge clock) q_io_write_0_valid <= w_io_write_0_valid;
  assign out[0:0] = q_io_write_0_valid;
  wire [7:0] w_io_write_0_bits_setIdx;
  reg [7:0] q_io_write_0_bits_setIdx;
  always @(posedge clock) q_io_write_0_bits_setIdx <= w_io_write_0_bits_setIdx;
  assign out[8:1] = q_io_write_0_bits_setIdx;
  wire [15:0] w_io_write_0_bits_entry_tag;
  reg [15:0] q_io_write_0_bits_entry_tag;
  always @(posedge clock) q_io_write_0_bits_entry_tag <= w_io_write_0_bits_entry_tag;
  assign out[24:9] = q_io_write_0_bits_entry_tag;
  wire [1:0] w_io_write_0_bits_entry_attribute_branchType;
  reg [1:0] q_io_write_0_bits_entry_attribute_branchType;
  always @(posedge clock) q_io_write_0_bits_entry_attribute_branchType <= w_io_write_0_bits_entry_attribute_branchType;
  assign out[26:25] = q_io_write_0_bits_entry_attribute_branchType;
  wire [1:0] w_io_write_0_bits_entry_attribute_rasAction;
  reg [1:0] q_io_write_0_bits_entry_attribute_rasAction;
  always @(posedge clock) q_io_write_0_bits_entry_attribute_rasAction <= w_io_write_0_bits_entry_attribute_rasAction;
  assign out[28:27] = q_io_write_0_bits_entry_attribute_rasAction;
  wire [3:0] w_io_write_0_bits_entry_position;
  reg [3:0] q_io_write_0_bits_entry_position;
  always @(posedge clock) q_io_write_0_bits_entry_position <= w_io_write_0_bits_entry_position;
  assign out[32:29] = q_io_write_0_bits_entry_position;
  wire [1:0] w_io_write_0_bits_entry_targetCarry_value;
  reg [1:0] q_io_write_0_bits_entry_targetCarry_value;
  always @(posedge clock) q_io_write_0_bits_entry_targetCarry_value <= w_io_write_0_bits_entry_targetCarry_value;
  assign out[34:33] = q_io_write_0_bits_entry_targetCarry_value;
  wire [19:0] w_io_write_0_bits_entry_targetLowerBits;
  reg [19:0] q_io_write_0_bits_entry_targetLowerBits;
  always @(posedge clock) q_io_write_0_bits_entry_targetLowerBits <= w_io_write_0_bits_entry_targetLowerBits;
  assign out[54:35] = q_io_write_0_bits_entry_targetLowerBits;
  wire [0:0] w_io_write_1_valid;
  reg [0:0] q_io_write_1_valid;
  always @(posedge clock) q_io_write_1_valid <= w_io_write_1_valid;
  assign out[55:55] = q_io_write_1_valid;
  wire [7:0] w_io_write_1_bits_setIdx;
  reg [7:0] q_io_write_1_bits_setIdx;
  always @(posedge clock) q_io_write_1_bits_setIdx <= w_io_write_1_bits_setIdx;
  assign out[63:56] = q_io_write_1_bits_setIdx;
  wire [15:0] w_io_write_1_bits_entry_tag;
  reg [15:0] q_io_write_1_bits_entry_tag;
  always @(posedge clock) q_io_write_1_bits_entry_tag <= w_io_write_1_bits_entry_tag;
  assign out[79:64] = q_io_write_1_bits_entry_tag;
  wire [1:0] w_io_write_1_bits_entry_attribute_branchType;
  reg [1:0] q_io_write_1_bits_entry_attribute_branchType;
  always @(posedge clock) q_io_write_1_bits_entry_attribute_branchType <= w_io_write_1_bits_entry_attribute_branchType;
  assign out[81:80] = q_io_write_1_bits_entry_attribute_branchType;
  wire [1:0] w_io_write_1_bits_entry_attribute_rasAction;
  reg [1:0] q_io_write_1_bits_entry_attribute_rasAction;
  always @(posedge clock) q_io_write_1_bits_entry_attribute_rasAction <= w_io_write_1_bits_entry_attribute_rasAction;
  assign out[83:82] = q_io_write_1_bits_entry_attribute_rasAction;
  wire [3:0] w_io_write_1_bits_entry_position;
  reg [3:0] q_io_write_1_bits_entry_position;
  always @(posedge clock) q_io_write_1_bits_entry_position <= w_io_write_1_bits_entry_position;
  assign out[87:84] = q_io_write_1_bits_entry_position;
  wire [1:0] w_io_write_1_bits_entry_targetCarry_value;
  reg [1:0] q_io_write_1_bits_entry_targetCarry_value;
  always @(posedge clock) q_io_write_1_bits_entry_targetCarry_value <= w_io_write_1_bits_entry_targetCarry_value;
  assign out[89:88] = q_io_write_1_bits_entry_targetCarry_value;
  wire [19:0] w_io_write_1_bits_entry_targetLowerBits;
  reg [19:0] q_io_write_1_bits_entry_targetLowerBits;
  always @(posedge clock) q_io_write_1_bits_entry_targetLowerBits <= w_io_write_1_bits_entry_targetLowerBits;
  assign out[109:90] = q_io_write_1_bits_entry_targetLowerBits;
  wire [0:0] w_io_write_2_valid;
  reg [0:0] q_io_write_2_valid;
  always @(posedge clock) q_io_write_2_valid <= w_io_write_2_valid;
  assign out[110:110] = q_io_write_2_valid;
  wire [7:0] w_io_write_2_bits_setIdx;
  reg [7:0] q_io_write_2_bits_setIdx;
  always @(posedge clock) q_io_write_2_bits_setIdx <= w_io_write_2_bits_setIdx;
  assign out[118:111] = q_io_write_2_bits_setIdx;
  wire [15:0] w_io_write_2_bits_entry_tag;
  reg [15:0] q_io_write_2_bits_entry_tag;
  always @(posedge clock) q_io_write_2_bits_entry_tag <= w_io_write_2_bits_entry_tag;
  assign out[134:119] = q_io_write_2_bits_entry_tag;
  wire [1:0] w_io_write_2_bits_entry_attribute_branchType;
  reg [1:0] q_io_write_2_bits_entry_attribute_branchType;
  always @(posedge clock) q_io_write_2_bits_entry_attribute_branchType <= w_io_write_2_bits_entry_attribute_branchType;
  assign out[136:135] = q_io_write_2_bits_entry_attribute_branchType;
  wire [1:0] w_io_write_2_bits_entry_attribute_rasAction;
  reg [1:0] q_io_write_2_bits_entry_attribute_rasAction;
  always @(posedge clock) q_io_write_2_bits_entry_attribute_rasAction <= w_io_write_2_bits_entry_attribute_rasAction;
  assign out[138:137] = q_io_write_2_bits_entry_attribute_rasAction;
  wire [3:0] w_io_write_2_bits_entry_position;
  reg [3:0] q_io_write_2_bits_entry_position;
  always @(posedge clock) q_io_write_2_bits_entry_position <= w_io_write_2_bits_entry_position;
  assign out[142:139] = q_io_write_2_bits_entry_position;
  wire [1:0] w_io_write_2_bits_entry_targetCarry_value;
  reg [1:0] q_io_write_2_bits_entry_targetCarry_value;
  always @(posedge clock) q_io_write_2_bits_entry_targetCarry_value <= w_io_write_2_bits_entry_targetCarry_value;
  assign out[144:143] = q_io_write_2_bits_entry_targetCarry_value;
  wire [19:0] w_io_write_2_bits_entry_targetLowerBits;
  reg [19:0] q_io_write_2_bits_entry_targetLowerBits;
  always @(posedge clock) q_io_write_2_bits_entry_targetLowerBits <= w_io_write_2_bits_entry_targetLowerBits;
  assign out[164:145] = q_io_write_2_bits_entry_targetLowerBits;
  wire [0:0] w_io_write_3_valid;
  reg [0:0] q_io_write_3_valid;
  always @(posedge clock) q_io_write_3_valid <= w_io_write_3_valid;
  assign out[165:165] = q_io_write_3_valid;
  wire [7:0] w_io_write_3_bits_setIdx;
  reg [7:0] q_io_write_3_bits_setIdx;
  always @(posedge clock) q_io_write_3_bits_setIdx <= w_io_write_3_bits_setIdx;
  assign out[173:166] = q_io_write_3_bits_setIdx;
  wire [15:0] w_io_write_3_bits_entry_tag;
  reg [15:0] q_io_write_3_bits_entry_tag;
  always @(posedge clock) q_io_write_3_bits_entry_tag <= w_io_write_3_bits_entry_tag;
  assign out[189:174] = q_io_write_3_bits_entry_tag;
  wire [1:0] w_io_write_3_bits_entry_attribute_branchType;
  reg [1:0] q_io_write_3_bits_entry_attribute_branchType;
  always @(posedge clock) q_io_write_3_bits_entry_attribute_branchType <= w_io_write_3_bits_entry_attribute_branchType;
  assign out[191:190] = q_io_write_3_bits_entry_attribute_branchType;
  wire [1:0] w_io_write_3_bits_entry_attribute_rasAction;
  reg [1:0] q_io_write_3_bits_entry_attribute_rasAction;
  always @(posedge clock) q_io_write_3_bits_entry_attribute_rasAction <= w_io_write_3_bits_entry_attribute_rasAction;
  assign out[193:192] = q_io_write_3_bits_entry_attribute_rasAction;
  wire [3:0] w_io_write_3_bits_entry_position;
  reg [3:0] q_io_write_3_bits_entry_position;
  always @(posedge clock) q_io_write_3_bits_entry_position <= w_io_write_3_bits_entry_position;
  assign out[197:194] = q_io_write_3_bits_entry_position;
  wire [1:0] w_io_write_3_bits_entry_targetCarry_value;
  reg [1:0] q_io_write_3_bits_entry_targetCarry_value;
  always @(posedge clock) q_io_write_3_bits_entry_targetCarry_value <= w_io_write_3_bits_entry_targetCarry_value;
  assign out[199:198] = q_io_write_3_bits_entry_targetCarry_value;
  wire [19:0] w_io_write_3_bits_entry_targetLowerBits;
  reg [19:0] q_io_write_3_bits_entry_targetLowerBits;
  always @(posedge clock) q_io_write_3_bits_entry_targetLowerBits <= w_io_write_3_bits_entry_targetLowerBits;
  assign out[219:200] = q_io_write_3_bits_entry_targetLowerBits;
  MainBtbWriteBufferEnq u_enq(.clock(clock), .reset(reset), .io_writeEntry_valid(r_io_writeEntry_valid), .io_writeEntry_bits_setIdx(r_io_writeEntry_bits_setIdx), .io_writeEntry_bits_wayMask(r_io_writeEntry_bits_wayMask), .io_writeEntry_bits_entry_tag(r_io_writeEntry_bits_entry_tag), .io_writeEntry_bits_entry_attribute_branchType(r_io_writeEntry_bits_entry_attribute_branchType), .io_writeEntry_bits_entry_attribute_rasAction(r_io_writeEntry_bits_entry_attribute_rasAction), .io_writeEntry_bits_entry_position(r_io_writeEntry_bits_entry_position), .io_writeEntry_bits_entry_targetCarry_value(r_io_writeEntry_bits_entry_targetCarry_value), .io_writeEntry_bits_entry_targetLowerBits(r_io_writeEntry_bits_entry_targetLowerBits), .io_flush_valid(r_io_flush_valid), .io_flush_bits_setIdx(r_io_flush_bits_setIdx), .io_flush_bits_wayMask(r_io_flush_bits_wayMask), .io_write_0_valid(w_io_write_0_valid), .io_write_0_bits_setIdx(w_io_write_0_bits_setIdx), .io_write_0_bits_entry_tag(w_io_write_0_bits_entry_tag), .io_write_0_bits_entry_attribute_branchType(w_io_write_0_bits_entry_attribute_branchType), .io_write_0_bits_entry_attribute_rasAction(w_io_write_0_bits_entry_attribute_rasAction), .io_write_0_bits_entry_position(w_io_write_0_bits_entry_position), .io_write_0_bits_entry_targetCarry_value(w_io_write_0_bits_entry_targetCarry_value), .io_write_0_bits_entry_targetLowerBits(w_io_write_0_bits_entry_targetLowerBits), .io_write_1_valid(w_io_write_1_valid), .io_write_1_bits_setIdx(w_io_write_1_bits_setIdx), .io_write_1_bits_entry_tag(w_io_write_1_bits_entry_tag), .io_write_1_bits_entry_attribute_branchType(w_io_write_1_bits_entry_attribute_branchType), .io_write_1_bits_entry_attribute_rasAction(w_io_write_1_bits_entry_attribute_rasAction), .io_write_1_bits_entry_position(w_io_write_1_bits_entry_position), .io_write_1_bits_entry_targetCarry_value(w_io_write_1_bits_entry_targetCarry_value), .io_write_1_bits_entry_targetLowerBits(w_io_write_1_bits_entry_targetLowerBits), .io_write_2_valid(w_io_write_2_valid), .io_write_2_bits_setIdx(w_io_write_2_bits_setIdx), .io_write_2_bits_entry_tag(w_io_write_2_bits_entry_tag), .io_write_2_bits_entry_attribute_branchType(w_io_write_2_bits_entry_attribute_branchType), .io_write_2_bits_entry_attribute_rasAction(w_io_write_2_bits_entry_attribute_rasAction), .io_write_2_bits_entry_position(w_io_write_2_bits_entry_position), .io_write_2_bits_entry_targetCarry_value(w_io_write_2_bits_entry_targetCarry_value), .io_write_2_bits_entry_targetLowerBits(w_io_write_2_bits_entry_targetLowerBits), .io_write_3_valid(w_io_write_3_valid), .io_write_3_bits_setIdx(w_io_write_3_bits_setIdx), .io_write_3_bits_entry_tag(w_io_write_3_bits_entry_tag), .io_write_3_bits_entry_attribute_branchType(w_io_write_3_bits_entry_attribute_branchType), .io_write_3_bits_entry_attribute_rasAction(w_io_write_3_bits_entry_attribute_rasAction), .io_write_3_bits_entry_position(w_io_write_3_bits_entry_position), .io_write_3_bits_entry_targetCarry_value(w_io_write_3_bits_entry_targetCarry_value), .io_write_3_bits_entry_targetLowerBits(w_io_write_3_bits_entry_targetLowerBits));
endmodule
