load("@rules_python//python:py_test.bzl", "py_test")

package(default_visibility = [
    "//:__pkg__",
    "//private:__subpackages__",
])

exports_files(
    glob(["**"]),
    visibility = ["//visibility:public"],
)

py_test(
    name = "merge_arguments_test",
    srcs = ["merge_arguments_test.py"],
    data = ["merge_arguments.py"],
)
