// A mock of XSTile for CoupledL2: the L2 flattened into a stand-in for its
// tile, so that its boundary is the tile's. Only the CHI link (and the node
// ID) leaves the design, as it leaves XSTile; CoupledL2's core-side signals
// (TileLink A-E from the core, the core's MMIO, prefetch training and
// control, the L2 TLB round trip, hints, feedback, errors, performance
// counters) end in a mock core inside the design.
//
// The mock core is harness, not a model of XiangShan's core: one register
// per core-side bit, outputs captured, inputs driven, and each input
// register fed by an output register XOR its neighbour in a ring, so no
// input is constant and every core-side path is one short register stage,
// as in the tile, where those signals meet logic a few microns away.
//
// CoupledL2.sv is generated (bazelisk run //:generate) and not committed.
module xstile_mock (
    input  logic clock,
    input  logic reset,
    output logic io_lcreditCHI_txsactive,
    input  logic io_lcreditCHI_rxsactive,
    output logic io_lcreditCHI_syscoreq,
    input  logic io_lcreditCHI_syscoack,
    output logic io_lcreditCHI_tx_linkactivereq,
    input  logic io_lcreditCHI_tx_linkactiveack,
    output logic io_lcreditCHI_tx_req_flitpend,
    output logic io_lcreditCHI_tx_req_flitv,
    output logic [124:0] io_lcreditCHI_tx_req_flit,
    input  logic io_lcreditCHI_tx_req_lcrdv,
    output logic io_lcreditCHI_tx_rsp_flitpend,
    output logic io_lcreditCHI_tx_rsp_flitv,
    output logic [50:0] io_lcreditCHI_tx_rsp_flit,
    input  logic io_lcreditCHI_tx_rsp_lcrdv,
    output logic io_lcreditCHI_tx_dat_flitpend,
    output logic io_lcreditCHI_tx_dat_flitv,
    output logic [384:0] io_lcreditCHI_tx_dat_flit,
    input  logic io_lcreditCHI_tx_dat_lcrdv,
    input  logic io_lcreditCHI_rx_linkactivereq,
    output logic io_lcreditCHI_rx_linkactiveack,
    input  logic io_lcreditCHI_rx_rsp_flitpend,
    input  logic io_lcreditCHI_rx_rsp_flitv,
    input  logic [50:0] io_lcreditCHI_rx_rsp_flit,
    output logic io_lcreditCHI_rx_rsp_lcrdv,
    input  logic io_lcreditCHI_rx_dat_flitpend,
    input  logic io_lcreditCHI_rx_dat_flitv,
    input  logic [384:0] io_lcreditCHI_rx_dat_flit,
    output logic io_lcreditCHI_rx_dat_lcrdv,
    input  logic io_lcreditCHI_rx_snp_flitpend,
    input  logic io_lcreditCHI_rx_snp_flitv,
    input  logic [87:0] io_lcreditCHI_rx_snp_flit,
    output logic io_lcreditCHI_rx_snp_lcrdv,
    input  logic [6:0] io_nodeID
);
  // 55 core-side outputs (811 bits) and 57 inputs (794 bits)
  logic [810:0] core_out, core_out_q;
  logic [793:0] core_in_q;
  always_ff @(posedge clock) begin
    core_out_q <= core_out;
    for (int k = 0; k < 794; k++)
      core_in_q[k] <= core_out_q[k % 811] ^ core_in_q[(k + 1) % 794];
  end

  CoupledL2 u_l2 (
      .clock(clock),
      .reset(reset),
      .auto_mmioBridge_mmio_in_a_ready(core_out[0]),
      .auto_mmioBridge_mmio_in_a_valid(core_in_q[0]),
      .auto_mmioBridge_mmio_in_a_bits_opcode(core_in_q[4:1]),
      .auto_mmioBridge_mmio_in_a_bits_param(core_in_q[7:5]),
      .auto_mmioBridge_mmio_in_a_bits_size(core_in_q[9:8]),
      .auto_mmioBridge_mmio_in_a_bits_source(core_in_q[14:10]),
      .auto_mmioBridge_mmio_in_a_bits_address(core_in_q[62:15]),
      .auto_mmioBridge_mmio_in_a_bits_user_memBackType_MM(core_in_q[63]),
      .auto_mmioBridge_mmio_in_a_bits_user_memPageType_NC(core_in_q[64]),
      .auto_mmioBridge_mmio_in_a_bits_mask(core_in_q[72:65]),
      .auto_mmioBridge_mmio_in_a_bits_data(core_in_q[136:73]),
      .auto_mmioBridge_mmio_in_a_bits_corrupt(core_in_q[137]),
      .auto_mmioBridge_mmio_in_d_ready(core_in_q[138]),
      .auto_mmioBridge_mmio_in_d_valid(core_out[1]),
      .auto_mmioBridge_mmio_in_d_bits_opcode(core_out[5:2]),
      .auto_mmioBridge_mmio_in_d_bits_param(core_out[7:6]),
      .auto_mmioBridge_mmio_in_d_bits_size(core_out[8]),
      .auto_mmioBridge_mmio_in_d_bits_source(core_out[13:9]),
      .auto_mmioBridge_mmio_in_d_bits_sink(core_out[14]),
      .auto_mmioBridge_mmio_in_d_bits_denied(core_out[15]),
      .auto_mmioBridge_mmio_in_d_bits_data(core_out[79:16]),
      .auto_mmioBridge_mmio_in_d_bits_corrupt(core_out[80]),
      .auto_in_a_ready(core_out[81]),
      .auto_in_a_valid(core_in_q[139]),
      .auto_in_a_bits_opcode(core_in_q[143:140]),
      .auto_in_a_bits_param(core_in_q[146:144]),
      .auto_in_a_bits_size(core_in_q[147]),
      .auto_in_a_bits_source(core_in_q[154:148]),
      .auto_in_a_bits_address(core_in_q[202:155]),
      .auto_in_a_bits_user_reqSource(core_in_q[207:203]),
      .auto_in_a_bits_user_alias(core_in_q[209:208]),
      .auto_in_a_bits_user_vaddr(core_in_q[253:210]),
      .auto_in_a_bits_user_needHint(core_in_q[254]),
      .auto_in_a_bits_echo_isKeyword(core_in_q[255]),
      .auto_in_a_bits_corrupt(core_in_q[256]),
      .auto_in_b_ready(core_in_q[257]),
      .auto_in_b_valid(core_out[82]),
      .auto_in_b_bits_opcode(core_out[85:83]),
      .auto_in_b_bits_param(core_out[87:86]),
      .auto_in_b_bits_address(core_out[135:88]),
      .auto_in_b_bits_data(core_out[391:136]),
      .auto_in_c_ready(core_out[392]),
      .auto_in_c_valid(core_in_q[258]),
      .auto_in_c_bits_opcode(core_in_q[261:259]),
      .auto_in_c_bits_param(core_in_q[262]),
      .auto_in_c_bits_size(core_in_q[263]),
      .auto_in_c_bits_source(core_in_q[270:264]),
      .auto_in_c_bits_address(core_in_q[318:271]),
      .auto_in_c_bits_data(core_in_q[574:319]),
      .auto_in_c_bits_corrupt(core_in_q[575]),
      .auto_in_d_ready(core_in_q[576]),
      .auto_in_d_valid(core_out[393]),
      .auto_in_d_bits_opcode(core_out[397:394]),
      .auto_in_d_bits_param(core_out[399:398]),
      .auto_in_d_bits_source(core_out[406:400]),
      .auto_in_d_bits_sink(core_out[414:407]),
      .auto_in_d_bits_denied(core_out[415]),
      .auto_in_d_bits_echo_isKeyword(core_out[416]),
      .auto_in_d_bits_data(core_out[672:417]),
      .auto_in_d_bits_corrupt(core_out[673]),
      .auto_in_e_valid(core_in_q[577]),
      .auto_in_e_bits_sink(core_in_q[585:578]),
      .auto_l3_pf_recv_in_addr(core_in_q[649:586]),
      .auto_l3_pf_recv_in_addr_valid(core_in_q[650]),
      .auto_l3_pf_recv_in_pf_en(core_in_q[651]),
      .auto_pf_recv_in_addr(core_in_q[715:652]),
      .auto_pf_recv_in_pf_source(core_in_q[720:716]),
      .auto_pf_recv_in_addr_valid(core_in_q[721]),
      .io_pfCtrlFromCore_l2_pf_master_en(core_in_q[722]),
      .io_pfCtrlFromCore_l2_pf_recv_en(core_in_q[723]),
      .io_pfCtrlFromCore_l2_pbop_en(core_in_q[724]),
      .io_pfCtrlFromCore_l2_vbop_en(core_in_q[725]),
      .io_pfCtrlFromCore_l2_cdp_en(core_in_q[726]),
      .io_pfCtrlFromCore_l2_pf_delay_latency(core_in_q[736:727]),
      .io_l2_fdbk_pf_ctrl_streamDegree(core_out[675:674]),
      .io_l2_fdbk_pf_ctrl_strideDegree(core_out[676]),
      .io_l2_fdbk_pf_ctrl_bertiDegree(core_out[677]),
      .io_l2_fdbk_pf_ctrl_smsDegree(core_out[678]),
      .io_l2_hint_0_valid(core_out[679]),
      .io_l2_hint_0_bits_sourceId(core_out[686:680]),
      .io_l2_hint_0_bits_isKeyword(core_out[687]),
      .io_l2_tlb_req_req_valid(core_out[688]),
      .io_l2_tlb_req_req_bits_vaddr(core_out[738:689]),
      .io_l2_tlb_req_req_bits_isPrefetch(core_out[739]),
      .io_l2_tlb_req_resp_valid(core_in_q[737]),
      .io_l2_tlb_req_resp_bits_paddr_0(core_in_q[785:738]),
      .io_l2_tlb_req_resp_bits_pbmt(core_in_q[787:786]),
      .io_l2_tlb_req_resp_bits_miss(core_in_q[788]),
      .io_l2_tlb_req_resp_bits_excp_0_gpf_ld(core_in_q[789]),
      .io_l2_tlb_req_resp_bits_excp_0_pf_ld(core_in_q[790]),
      .io_l2_tlb_req_resp_bits_excp_0_af_ld(core_in_q[791]),
      .io_l2_tlb_req_pmp_resp_ld(core_in_q[792]),
      .io_l2_tlb_req_pmp_resp_mmio(core_in_q[793]),
      .io_l2Miss(core_out[740]),
      .io_error_valid(core_out[741]),
      .io_error_address(core_out[789:742]),
      .io_lcreditCHI_txsactive(io_lcreditCHI_txsactive),
      .io_lcreditCHI_rxsactive(io_lcreditCHI_rxsactive),
      .io_lcreditCHI_syscoreq(io_lcreditCHI_syscoreq),
      .io_lcreditCHI_syscoack(io_lcreditCHI_syscoack),
      .io_lcreditCHI_tx_linkactivereq(io_lcreditCHI_tx_linkactivereq),
      .io_lcreditCHI_tx_linkactiveack(io_lcreditCHI_tx_linkactiveack),
      .io_lcreditCHI_tx_req_flitpend(io_lcreditCHI_tx_req_flitpend),
      .io_lcreditCHI_tx_req_flitv(io_lcreditCHI_tx_req_flitv),
      .io_lcreditCHI_tx_req_flit(io_lcreditCHI_tx_req_flit),
      .io_lcreditCHI_tx_req_lcrdv(io_lcreditCHI_tx_req_lcrdv),
      .io_lcreditCHI_tx_rsp_flitpend(io_lcreditCHI_tx_rsp_flitpend),
      .io_lcreditCHI_tx_rsp_flitv(io_lcreditCHI_tx_rsp_flitv),
      .io_lcreditCHI_tx_rsp_flit(io_lcreditCHI_tx_rsp_flit),
      .io_lcreditCHI_tx_rsp_lcrdv(io_lcreditCHI_tx_rsp_lcrdv),
      .io_lcreditCHI_tx_dat_flitpend(io_lcreditCHI_tx_dat_flitpend),
      .io_lcreditCHI_tx_dat_flitv(io_lcreditCHI_tx_dat_flitv),
      .io_lcreditCHI_tx_dat_flit(io_lcreditCHI_tx_dat_flit),
      .io_lcreditCHI_tx_dat_lcrdv(io_lcreditCHI_tx_dat_lcrdv),
      .io_lcreditCHI_rx_linkactivereq(io_lcreditCHI_rx_linkactivereq),
      .io_lcreditCHI_rx_linkactiveack(io_lcreditCHI_rx_linkactiveack),
      .io_lcreditCHI_rx_rsp_flitpend(io_lcreditCHI_rx_rsp_flitpend),
      .io_lcreditCHI_rx_rsp_flitv(io_lcreditCHI_rx_rsp_flitv),
      .io_lcreditCHI_rx_rsp_flit(io_lcreditCHI_rx_rsp_flit),
      .io_lcreditCHI_rx_rsp_lcrdv(io_lcreditCHI_rx_rsp_lcrdv),
      .io_lcreditCHI_rx_dat_flitpend(io_lcreditCHI_rx_dat_flitpend),
      .io_lcreditCHI_rx_dat_flitv(io_lcreditCHI_rx_dat_flitv),
      .io_lcreditCHI_rx_dat_flit(io_lcreditCHI_rx_dat_flit),
      .io_lcreditCHI_rx_dat_lcrdv(io_lcreditCHI_rx_dat_lcrdv),
      .io_lcreditCHI_rx_snp_flitpend(io_lcreditCHI_rx_snp_flitpend),
      .io_lcreditCHI_rx_snp_flitv(io_lcreditCHI_rx_snp_flitv),
      .io_lcreditCHI_rx_snp_flit(io_lcreditCHI_rx_snp_flit),
      .io_lcreditCHI_rx_snp_lcrdv(io_lcreditCHI_rx_snp_lcrdv),
      .io_nodeID(io_nodeID),
      .io_perf_1_value(core_out[795:790]),
      .io_perf_2_value(core_out[796]),
      .io_perf_4_value(core_out[797]),
      .io_perf_5_value(core_out[798]),
      .io_perf_6_value(core_out[799]),
      .io_perf_7_value(core_out[800]),
      .io_perf_8_value(core_out[801]),
      .io_perf_9_value(core_out[802]),
      .io_perf_10_value(core_out[803]),
      .io_perf_11_value(core_out[804]),
      .io_perf_12_value(core_out[805]),
      .io_perf_13_value(core_out[806]),
      .io_perf_14_value(core_out[807]),
      .io_perf_15_value(core_out[808]),
      .io_perf_16_value(core_out[809]),
      .io_perf_17_value(core_out[810])
  );
endmodule
