name: bazel-orfs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: bazel-orfs unit tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          docker-images: true
          large-packages: false
          swap-storage: false
      - name: Checkout bazel-orfs
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Launch Bazel
        run: bazelisk build --nobuild ... --build_tests_only --profile=launch.profile
      - name: Analyze launch
        if: always()
        run: bazelisk analyze-profile launch.profile

      - name: Build tests
        run: bazelisk build ... --build_tests_only --profile=build.profile
      - name: Analyze build
        if: always()
        run: bazelisk analyze-profile build.profile

      - name: Run tests
        run: bazelisk test ... --keep_going --build_tests_only --test_output=errors --profile=test.profile
      - name: Analyze test
        if: always()
        run: bazelisk analyze-profile test.profile

  orfs-lint:
    name: ORFS lint
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          docker-images: true
          large-packages: false
          swap-storage: false
      - name: Checkout bazel-orfs
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-orfs-lint
          repository-cache: true

      - name: ORFS integration lint tests
        working-directory: orfs
        run: bazelisk test //:asap7_lint_tests --keep_going --test_output=errors

  orfs-real:
    name: ORFS real flow (gcd)
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          docker-images: true
          large-packages: false
          swap-storage: false
      - name: Checkout bazel-orfs
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-orfs-real
          repository-cache: true

      - name: ORFS real flow test (gcd)
        working-directory: orfs
        run: bazelisk test @orfs//flow/designs/asap7/gcd:gcd_test --test_output=errors
