name: bazel-orfs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          docker-images: true
          large-packages: false
          swap-storage: false
      - name: Checkout bazel-orfs
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Test
        run: bazelisk test ... --keep_going --build_tests_only --test_output=errors --profile=build.profile
      - name: Analyze profile
        if: always()
        run: bazelisk analyze-profile build.profile
