"""Figures for the study, generated from the checked-in result JSONs.

Same convention as test/estimation_ladder/update_readme.py: Agg backend,
PNGs written beside the results, regenerated by a bazel run rather than
edited. A figure that cannot be rebuilt from the JSONs is a claim nobody
can check.

Palette and form follow the data-viz reference instance unchanged:

  * categorical slots in fixed order, never cycled;
  * one axis per panel -- two measures of different scale become two
    panels, never a second y-axis;
  * forms that put every pair of series on screen at once (scatter, small
    multiples) cap at the first three slots, which are the ones that
    validate all-pairs;
  * recessive grid and axes, thin marks, legend whenever there are two or
    more series;
  * aqua, yellow and magenta sit below 3:1 on the light surface, so every
    figure ships beside the table it was generated from -- that is the
    documented relief for those slots.
"""

import argparse
import json
import os
import re
import statistics as st
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

# Categorical slots, fixed order.
SERIES = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300"]
SURFACE = "#fcfcfb"
INK = "#0b0b0b"
INK_2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
AXIS = "#c3c2b7"
BAND = "#cde2fb"

STAGE_ORDER = ["2_floorplan", "3_place", "4_cts", "5_1_grt"]
STAGE_LABEL = {
    "2_floorplan": "floorplan",
    "3_place": "place",
    "4_cts": "cts",
    "5_1_grt": "grt",
}


def style(ax):
    """Recessive chrome: the data is the only assertive thing on the page."""
    ax.set_facecolor(SURFACE)
    ax.grid(True, color=GRID, linewidth=0.8, zorder=0)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS)
        ax.spines[side].set_linewidth(1.0)
    ax.tick_params(colors=MUTED, labelsize=9, length=0)
    ax.xaxis.label.set_color(INK_2)
    ax.yaxis.label.set_color(INK_2)


def title(ax, text, sub=None):
    ax.set_title(text, color=INK, fontsize=12, loc="left", pad=14 if sub else 8)
    if sub:
        ax.text(
            0.0,
            1.02,
            sub,
            transform=ax.transAxes,
            color=MUTED,
            fontsize=9,
            va="bottom",
        )


def load_group(results, prefix, key_re):
    """Read `<prefix>_<key>_<stage>.json` into {key: {stage: data}}."""
    out = {}
    for path in sorted(Path(results).glob(prefix + "*.json")):
        m = re.search(key_re, path.name)
        if not m:
            continue
        data = json.loads(path.read_text())
        out.setdefault(m.group(1), {})[data["stage"]] = data
    return out


def fig_ladder(results, out):
    """min_period by stage, one line per shape."""
    shapes = load_group(
        results,
        "shape_ladder_",
        r"^shape_ladder_(.+)_(?:floorplan|place|cts|grt)\.json$",
    )
    if not shapes:
        return None
    fig, ax = plt.subplots(figsize=(7.2, 4.2), facecolor=SURFACE)
    for i, name in enumerate(sorted(shapes)):
        rungs = shapes[name]
        xs = [s for s in STAGE_ORDER if s in rungs]
        ys = [rungs[s]["min_period"] for s in xs]
        ax.plot(
            [STAGE_LABEL[s] for s in xs],
            ys,
            color=SERIES[i % len(SERIES)],
            linewidth=2,
            marker="o",
            markersize=7,
            markeredgecolor=SURFACE,
            markeredgewidth=1.5,
            label=name,
            zorder=3,
        )
    style(ax)
    ax.margins(y=0.10)
    ax.set_ylabel("min_period = clk_period - WNS  (ps)")
    title(
        ax,
        "The pre-route estimate is a different number at every stage",
        "floorplan is identical for every shape: it has no placement, so it prices no wire",
    )
    ax.legend(
        frameon=False,
        fontsize=9,
        labelcolor=INK_2,
        ncol=3,
        loc="lower right",
    )
    fig.tight_layout()
    fig.savefig(out, dpi=120, facecolor=SURFACE)
    plt.close(fig)
    return out


def fig_gap_vs_contention(results, out):
    """The place-to-grt gap against how contended the worst layer is."""
    shapes = load_group(
        results,
        "shape_ladder_",
        r"^shape_ladder_(.+)_(?:floorplan|place|cts|grt)\.json$",
    )
    points = []
    for name, rungs in shapes.items():
        layers_path = Path(results) / ("shape_layers_%s.json" % name)
        if not layers_path.exists() or "3_place" not in rungs:
            continue
        layers = json.loads(layers_path.read_text())
        routable = [x for x in layers["layers"] if x.get("routable")]
        if not routable:
            continue
        worst = max(routable, key=lambda x: x["effective_utilization_percent"])
        gap = (
            (rungs["3_place"]["min_period"] - rungs["5_1_grt"]["min_period"])
            / rungs["5_1_grt"]["min_period"]
            * 100.0
        )
        points.append((worst["effective_utilization_percent"], gap, name))
    if not points:
        return None
    points.sort()
    fig, ax = plt.subplots(figsize=(7.2, 4.2), facecolor=SURFACE)
    ax.axhline(0.0, color=AXIS, linewidth=1.0, zorder=1)
    ax.axvline(100.0, color=MUTED, linewidth=1.0, linestyle=(0, (4, 3)), zorder=1)
    ax.plot(
        [p[0] for p in points],
        [p[1] for p in points],
        color=SERIES[0],
        linewidth=2,
        marker="o",
        markersize=8,
        markeredgecolor=SURFACE,
        markeredgewidth=1.5,
        zorder=3,
    )
    for x, y, name in points:
        ax.annotate(
            name,
            (x, y),
            textcoords="offset points",
            xytext=(0, -16),
            ha="center",
            color=INK_2,
            fontsize=8,
        )
    ax.text(
        101,
        ax.get_ylim()[1],
        "over capacity",
        color=MUTED,
        fontsize=8,
        va="top",
    )
    style(ax)
    ax.set_xlabel("most contended routable layer  (% of the tracks the router may spend)")
    ax.set_ylabel("place vs grt  (% of min_period)")
    title(
        ax,
        "Placement and global route only disagree once a layer runs out of tracks",
        "with room to route, grt takes the direct path and confirms what placement said",
    )
    fig.tight_layout()
    fig.savefig(out, dpi=120, facecolor=SURFACE)
    plt.close(fig)
    return out


def fig_layers(results, shape, out):
    """Per-layer routing demand as a share of what the router may spend."""
    path = Path(results) / ("shape_layers_%s.json" % shape)
    if not path.exists():
        return None
    layers = [x for x in json.loads(path.read_text())["layers"] if x.get("routable")]
    if not layers:
        return None
    names = [x["layer"] for x in layers]
    used = [x["effective_utilization_percent"] for x in layers]
    # Magnitude by category, one measure: a single series, so the top of
    # the stack is called out by annotation rather than by a second hue.
    colors = [SERIES[0] if x["level"] < 8 else SERIES[1] for x in layers]
    fig, ax = plt.subplots(figsize=(7.2, 4.0), facecolor=SURFACE)
    ax.axhline(100.0, color=MUTED, linewidth=1.0, linestyle=(0, (4, 3)), zorder=2)
    ax.bar(names, used, color=colors, width=0.62, zorder=3)
    for name, value, layer in zip(names, used, layers):
        ax.annotate(
            "%.0f%%" % value,
            (name, value),
            textcoords="offset points",
            xytext=(0, 4),
            ha="center",
            color=INK_2,
            fontsize=8,
        )
    ax.text(
        len(names) - 0.4,
        102,
        "capacity",
        color=MUTED,
        fontsize=8,
        ha="right",
        va="bottom",
    )
    style(ax)
    ax.set_ylabel("routing demand  (% of tracks the router may spend)")
    title(
        ax,
        "The design does reach the top of the stack -- and M2 is over capacity",
        "M8/M9 in orange: permitted by MAX_ROUTING_LAYER=M9, and actually used",
    )
    fig.tight_layout()
    fig.savefig(out, dpi=120, facecolor=SURFACE)
    plt.close(fig)
    return out


def fig_knobs_vs_noise(results, out):
    """The study's headline: knob effects against the flow's own spread.

    Two panels, not two y-axes: min_period in ps and runtime in seconds
    are different scales, and a dual axis would invite reading a crossing
    as meaning something.
    """
    seeds = load_group(
        results,
        "seed_ladder_",
        r"^seed_ladder_(\d+)_(?:place|grt)\.json$",
    )
    ensemble = [
        r["5_1_grt"]["min_period"] for r in seeds.values() if "5_1_grt" in r
    ]

    period, cost = {}, {}
    for path in sorted(Path(results).glob("policy_*t*_s*.json")):
        m = re.search(r"policy_(cost_)?t(\d+)_s(\d+)\.json$", path.name)
        if not m:
            continue
        data = json.loads(path.read_text())
        tns = int(m.group(2))
        if m.group(1):
            cost.setdefault(tns, []).append(data["stages"]["5_1_grt"])
        else:
            period.setdefault(tns, []).append(data["min_period"])
    if not period or not ensemble:
        return None

    fig, axes = plt.subplots(1, 2, figsize=(9.6, 4.4), facecolor=SURFACE)
    arms = sorted(period)

    for ax, data, label, unit in (
        (axes[0], period, "min_period  (ps)", "ps"),
        (axes[1], cost, "global route stage  (s)", "s"),
    ):
        for i, tns in enumerate(arms):
            values = data[tns]
            mean = st.mean(values)
            two = 2 * st.stdev(values) if len(values) > 1 else 0.0
            ax.scatter(
                [i] * len(values),
                values,
                color=SERIES[i],
                s=26,
                alpha=0.55,
                edgecolor=SURFACE,
                linewidth=0.6,
                zorder=3,
            )
            ax.errorbar(
                i,
                mean,
                yerr=two / 2,
                color=SERIES[i],
                marker="o",
                markersize=9,
                markeredgecolor=SURFACE,
                markeredgewidth=1.5,
                capsize=5,
                linewidth=2,
                zorder=4,
            )
            ax.annotate(
                "%.4g %s" % (mean, unit),
                (i, mean),
                textcoords="offset points",
                xytext=(12, 0),
                va="center",
                color=INK_2,
                fontsize=9,
            )
        style(ax)
        ax.set_xticks(range(len(arms)))
        ax.set_xticklabels(["TNS=%d" % t for t in arms])
        ax.set_ylabel(label)

    title(axes[0], "Coverage buys no period", "12 seeds per arm, bars 1 sigma")
    title(axes[1], "but half the stage runtime", "same seeds; only TNS=0 clears 2 sigma")
    # Headroom so the extreme seed does not sit on the frame.
    for ax in axes:
        ax.margins(y=0.12)
    fig.tight_layout()
    fig.savefig(out, dpi=120, facecolor=SURFACE)
    plt.close(fig)
    return out


def fig_rc_transfer(results, out):
    """What transfers between designs and what does not.

    Resistance and capacitance are both plotted as fitted/platform
    ratios, so they are the same dimensionless scale and belong on one
    axis -- this is the case where two series is right and a second
    y-axis would be wrong.
    """
    path = Path(results) / "rc_fit.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    fitted, platform = data["fitted_layers"], data["platform_layers"]
    layers = sorted(
        (name for name in fitted if name in platform),
        key=lambda name: platform[name].get("level", int(name[1:])),
    )
    if not layers:
        return None

    res = [fitted[n]["resistance"] / platform[n]["resistance"] for n in layers]
    cap = [fitted[n]["capacitance"] / platform[n]["capacitance"] for n in layers]

    fig, ax = plt.subplots(figsize=(7.4, 4.2), facecolor=SURFACE)
    ax.axhline(1.0, color=MUTED, linewidth=1.0, linestyle=(0, (4, 3)), zorder=2)
    for values, colour, label in (
        (res, SERIES[0], "resistance"),
        (cap, SERIES[1], "capacitance"),
    ):
        ax.plot(
            layers,
            values,
            color=colour,
            linewidth=2,
            marker="o",
            markersize=8,
            markeredgecolor=SURFACE,
            markeredgewidth=1.5,
            label=label,
            zorder=3,
        )
    ax.annotate(
        "the platform's value",
        (len(layers) - 1, 1.0),
        textcoords="offset points",
        xytext=(-4, 7),
        ha="right",
        color=MUTED,
        fontsize=8,
    )
    style(ax)
    ax.margins(y=0.14)
    ax.set_ylabel("this design's fit / the platform's value")
    title(
        ax,
        "Resistance transfers between designs; capacitance does not",
        "one fit on one design, against values fitted from four others",
    )
    ax.legend(frameon=False, fontsize=9, labelcolor=INK_2, loc="lower left")
    fig.tight_layout()
    fig.savefig(out, dpi=120, facecolor=SURFACE)
    plt.close(fig)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", required=True)
    ap.add_argument("--shape", default="u55_derated")
    args = ap.parse_args()

    results = Path(args.results)
    if not results.is_absolute():
        # Under `bazelisk run` the working directory is the runfiles tree.
        # The results are checked-in sources and the figures belong beside
        # them, so both ends resolve against the workspace -- the same way
        # inventory.py writes its output.
        workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
        if workspace:
            results = Path(workspace) / results
    if not results.is_dir():
        raise SystemExit("no results directory at %s" % results)
    written = [
        fig_ladder(results, results / "fig_ladder.png"),
        fig_gap_vs_contention(results, results / "fig_gap_vs_contention.png"),
        fig_layers(results, args.shape, results / "fig_layers.png"),
        fig_knobs_vs_noise(results, results / "fig_knobs_vs_noise.png"),
        fig_rc_transfer(results, results / "fig_rc_transfer.png"),
    ]
    for path in written:
        print("wrote %s" % path if path else "skipped a figure: inputs absent")


if __name__ == "__main__":
    main()
